### PR TITLE
Update chgres_cube documentation to cover warning and fix for duplicate grib2 entries when concatenating files

### LINKED ISSUE #778: Duplicate GRIB2 vertical levels and chgres_cube - add documentation
Error handling was recently added to stop processing in chgres_cube when duplicate vertical levels were encountered (See #763). This can happen when users don't use officially supported GRIB2 data. For example, users have created their own GRIB2 files by concatenating multiple, smaller files.

Duplicate levels are easily removed using tools such as wgrib2. Provide documentation so the user can properly prepare their non-standard GRIB2 file.

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
Add documentation to describe how concatenation of grib2 files can result in duplicate variables and levels, causing chgres_cube to exit with a warning.  Provide an example wgrib2 command/script that will strip concatenated grib2 files of duplicate entries.

## TESTS CONDUCTED: 
No tests conducted, since only documentation was changed.

## DEPENDENCIES:
None.

## DOCUMENTATION:
Changed in both the global and regional chgres_cube sections.

## ISSUE:
Fixes #778.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA I ran the readthedocs: https://jeff-beck.readthedocs.io/en/grib2_duplication/ufs_utils.html#initializing-global-domains-with-grib2-data-some-caveats

The formatting of the Perl script section looks odd to me.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA I ran the readthedocs: https://jeff-beck.readthedocs.io/en/grib2_duplication/ufs_utils.html#initializing-global-domains-with-grib2-data-some-caveats
> 
> The formatting of the Perl script section looks odd to me.

Thanks, @GeorgeGayno-NOAA!  I've made some syntax modifications.  Can you try rerunning RTD?  Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA I reran the 'readthedocs'. Does this look correct?

https://jeff-beck.readthedocs.io/en/grib2_duplication/ufs_utils.html#initializing-global-domains-with-grib2-data-some-caveats
https://jeff-beck.readthedocs.io/en/grib2_duplication/ufs_utils.html#initializing-regional-domains-with-grib2-data-some-caveats

**Comment by JeffBeck-NOAA** [comment]
@GeorgeGayno-NOAA, yes, everything looks good!  Please let me know if you have any comments regarding the content.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Approved. Update your branch from 'develop' and I will merge.

**Comment by JeffBeck-NOAA** [comment]
> Approved. Update your branch from 'develop' and I will merge.

@GeorgeGayno-NOAA, branch updated!

**Pull request merged**
