### PR TITLE
Remove the module use line for esmf/8.4.1 on WCOSS2

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## DESCRIPTION OF CHANGES: 
Remove the module use line for esmf/8.4.1 on WCOSS2. This change is needed for HAFSv1 code delivery.

## TESTS CONDUCTED: 
The esmf/8.4.1 on WCOSS2 will be moved from dev to prod installation area, which is expected to be done by NCO/GDIT in the next 2-3 days. Thus the module use line will be on longer needed.

### CODE REVIEW

**Comment by BinLiu-NOAA** [comment]
@GeorgeGayno-NOAA, I am not sure what is the best way to move forward. But, apparently, we cannot test on WCOSS2 at this point, since the esmf/8.4.1 module installation area move is not done yet.

However, we do need a release tag or a branch to use for HAFSv1 code delivery today.

Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA, I am not sure what is the best way to move forward. But, apparently, we cannot test on WCOSS2 at this point, since the esmf/8.4.1 module installation area move is not done yet.
> 
> However, we do need a release tag or a branch to use for HAFSv1 code delivery today.
> 
> Thanks!

So, should I create a tag from the head of 'develop' (4f613fe)? Then, I will need to create another tag later this week when NCO installs ESMF in prod location?

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA ESMF v8.4.1 is available under prod now. Can you test your branch?

**Comment by BinLiu-NOAA** [comment]
@GeorgeGayno-NOAA, Yes, I tested yesterday (04/12) on Dogwood. It worked fine. And I believe it will be on Cactus prod area today (04/13) as well.

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA Your branch is not up-to-date with 'develop'. For some reason, the pull request is not indicating this problem. The reason may be because you don't have a 'develop' branch in your fork. I recommend that all forks contain a 'develop' branch and that you always keep your fork's version up-to-date with 'develop' in the authoritative repository.

**Comment by BinLiu-NOAA** [comment]
@GeorgeGayno-NOAA, Since I cannot change the production/hafs.v1 branch at this point, I am closing this PR. Will use another PR branch to update UFS_UTILS develop branch.

BTW, I just pushed the latest develop branch into the hafs-community fork of UFS_UTILS.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA, Since I cannot change the production/hafs.v1 branch at this point, I am closing this PR. Will use another PR branch to update UFS_UTILS develop branch.
> 
> BTW, I just pushed the latest develop branch into the hafs-community fork of UFS_UTILS.

Always create new branches off your fork's 'develop' branch. And keep your fork's 'develop' branch up-to-date with the authoritative repository.

**Pull request closed without merging**
