### PR TITLE
Update documentation for SRW APP

### LINKED ISSUE #643: Update documentation to support SRW APP v2.0
The 'read the docs' documentation needs to be updated. 

- chgres_cube now supports the WAM - new namelist option, etc.
- sfc_climo_gen now supports VIIRS-based vegetation type data.
- chgres_cube - varmap table changes. See #556. 
- chgres_cube - new GRIB2 humidity processing (new routines "use_rh" and "calrh").  #566
- orog_gsl - new orography generation program that outputs fields for the GSL GWD.
- vcoord_gen.fd - new utility to generate user-defined hybrid levels.
- New programs inland.fd and lake.fd.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Update the doxygen and readthedocs documentation to support v2.0 of the SRW App.

## TESTS CONDUCTED: 
N/A.

## DEPENDENCIES:
None.

## DOCUMENTATION:
The doxygen was created and placed here: https://www.emc.ncep.noaa.gov/jcsda/ggayno/doxygen/html/index.html

The readthedocs is here: https://georgegayno-noaaufs-utils.readthedocs.io/en/feature-srw_doc/index.html#

## ISSUE: 
Fixes #643.

## CONTRIBUTORS (optional): 
@mdtoy @JeffBeck-NOAA @LarissaReames-NOAA

### CODE REVIEW

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA @LarissaReames-NOAA  - I will update the 'gh-pages' branch. Before I create the tag, can we have the EPIC folks do one final test using 'develop' at a2b0817. Who is the person to contact?

**Comment by JeffBeck-NOAA** [comment]
@GeorgeGayno-NOAA, I'm tagging @mark-a-potts to ask about the status of testing.

**Comment by mark-a-potts** [comment]
What kind(s) of tests should be run?

**Comment by JeffBeck-NOAA** [comment]
@mark-a-potts, I would think the fundamental tests listed in this [PR](https://github.com/ufs-community/ufs-srweather-app/issues/277) would be fine.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, do you have a list of your proposed fundamental tests?  I see them in your PR documentation, but was just wondering if you had them listed somewhere.  Thanks!

**Comment by gsketefian** [comment]
@JeffBeck-NOAA There is a list of tests in [this google sheet](https://docs.google.com/spreadsheets/d/1WZDnO7NT1NjZxa09QlknCWkEAn65AFrHvXbXdYppTAE/edit#gid=1036071272) (the rows highlighted in blue are the proposed fundamental tests).  A discussion of the issue can be found at Issue #[277](https://github.com/ufs-community/ufs-srweather-app/issues/277).

**Pull request merged**
