### PR TITLE
Updating Doxyfile.in files due to doxygen warnings

### LINKED ISSUE #417: Doxyfiles need to be updated
I see this for all Doxyfiles on the CI:

```
warning: Tag 'TCL_SUBST' at line 227 of file '/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/build/sorc/global_cycle.fd/docs/Doxyfile' has become obsolete.
240
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
241
warning: Tag 'COLS_IN_ALPHA_INDEX' at line 1007 of file '/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/build/sorc/global_cycle.fd/docs/Doxyfile' has become obsolete.
242
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
243
warning: argument 'a4wide' for option PAPER_TYPE is not a valid enum value
```

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #417 
Updating Doxyfile.in files due to doxygen warnings.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett I still am seeing warnings, such as `Tag 'TCL_SUBST' at line 227 of file `

**Comment by edwardhartnett** [comment]
OK, while this PR was open, ubuntu-latest upgraded to doxygen 1.9.1. ;-)

I have rerun doxygen -u on all the Doxyfile.in files, to eliminate warnings and bring them up to date with doxygen 1.9.1 standards.

I had to build doxygen-1.9.1 from source to get it on my machine. ;-)

**Comment by edwardhartnett** [comment]
I have updated the documentation on gh-pages to the latest documentation build, using doxygen 1.9.1.

**Comment by edwardhartnett** [comment]
OK, now we're down to just one last doxygen warning I can't figure out how to get rid of. ;-)

**Comment by edwardhartnett** [comment]
OK, I think this is good to go. @GeorgeGayno-NOAA please take another look, and approve it if you agree.

**Comment by GeorgeGayno-NOAA** [comment]
I am still seeing doxygen warnings for the ubuntu builds. Example:

`warning: ignoring unsupported tag 'PYTHON_DOCSTRING' at line 226, file /home/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/build/sorc/emcsfc_snow2mdl.fd/docs/Doxyfile`

(Each release of doxygen seems sensitive to these 'tags'.  On Dell, it does not like several other tags. I wonder if we can ever get rid of them)

**Comment by edwardhartnett** [comment]
We will focus our efforts on the doxygen version released with ubuntu-latest, which is 1.9.1. And for that version, as we see in the output of the builds, there are no warnings.

**Comment by GeorgeGayno-NOAA** [comment]
> We will focus our efforts on the doxygen version released with ubuntu-latest, which is 1.9.1. And for that version, as we see in the output of the builds, there are no warnings.

Sounds good.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Warnings are removed when using doxygen 1.9.1 - which is our target doxygen version.

**Pull request merged**
