### PR TITLE
Correct some comment documentation about new surface processing variables.

### PR DESCRIPTION
**Pull request by LarissaReames**
Addresses Issue #193.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA 'develop' was updated recently.  Please merge the latest changes to your branch.

**Comment by LarissaReames-NOAA** [comment]
> @LarissaReames-NOAA 'develop' was updated recently. Please merge the latest changes to your branch.

Done.

**Comment by GeorgeGayno-NOAA** [comment]
> > @LarissaReames-NOAA 'develop' was updated recently. Please merge the latest changes to your branch.
> 
> Done.

Sorry @LarissaReames-NOAA It looks like my colleague made another update just before your merge.  Do another merge to your branch.  Then I will merge your changes.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Approved.

**Pull request merged**
