### PR TITLE
[develop] Configs for compiling and running online-cmaq on cheyenne.

### PR DESCRIPTION
**Pull request by padhrigmccarthy**
## DESCRIPTION OF CHANGES: 
UFS_UTILS config modules for Cheyenne HPC. These were developed in order to compile/run online-cmaq on Cheyenne with the new workflow. Tested successfully on cheyenne intel.

## TESTS CONDUCTED: 
I have compiled and run a version of the community config on Cheyenne, but I have not run formal tests from the test harness. Let me know if you would like me to contribute the config.yaml I developed for this purpose.

## DEPENDENCIES:
[PR with cheyenne configs for the ufs_weather_model](https://github.com/ufs-community/ufs-srweather-app/pull/656)

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
As a heads up for the repository managers, please open an issue first before starting any work.

**Comment by padhrigmccarthy** [comment]
> As a heads up for the repository managers, please open an issue first before starting any work.

@GeorgeGayno-NOAA Apologies. I'm new to this, and have been working to get SRW online-cmaq running on Cheyenne. I didn't realize I'd be contributing to three different repos. Thanks for the guidance.

**Comment by padhrigmccarthy** [comment]
I'll need some assistance interpreting the failed check. It seems 100% of tests were successful, but the check failed anyway:

> 100% tests passed, 0 tests failed out of 29
> 
> Total Test time (real) =  19.69 sec
> + gcovr --root .. -v --html-details --exclude ../tests --exclude CMakeFiles --print-summary -o test-coverage.html
> Error: Process completed with exit code 1.

**Comment by GeorgeGayno-NOAA** [comment]
> I'll need some assistance interpreting the failed check. It seems 100% of tests were successful, but the check failed anyway:
> 
> > 100% tests passed, 0 tests failed out of 29
> > Total Test time (real) =  19.69 sec
> > 
> > * gcovr --root .. -v --html-details --exclude ../tests --exclude CMakeFiles --print-summary -o test-coverage.html
> >   Error: Process completed with exit code 1.

I don't know why it failed. I don't think it is anything you did. Let me rerun it. These tests break a lot. We are trying to make them more robust.

**Comment by GeorgeGayno-NOAA** [comment]
> > I'll need some assistance interpreting the failed check. It seems 100% of tests were successful, but the check failed anyway:
> > > 100% tests passed, 0 tests failed out of 29
> > > Total Test time (real) =  19.69 sec
> > > 
> > > * gcovr --root .. -v --html-details --exclude ../tests --exclude CMakeFiles --print-summary -o test-coverage.html
> > >   Error: Process completed with exit code 1.
> 
> I don't know why it failed. I don't think it is anything you did. Let me rerun it. These tests break a lot. We are trying to make them more robust.

It looks like gcovr was updated yesterday: https://gcovr.com/en/stable/changelog.html#march-2023

And my workflows are breaking in the same way. So this won't hold up approval of your PRs.

**Comment by padhrigmccarthy** [comment]
> It looks like gcovr was updated yesterday: https://gcovr.com/en/stable/changelog.html#march-2023
> 
> And my workflows are breaking in the same way. So this won't hold up approval of your PRs.

Thanks, George!

**Comment by GeorgeGayno-NOAA** [comment]
> > As a heads up for the repository managers, please open an issue first before starting any work.
> 
> @GeorgeGayno-NOAA Apologies. I'm new to this, and have been working to get SRW online-cmaq running on Cheyenne. I didn't realize I'd be contributing to three different repos. Thanks for the guidance.

No problem. See our wiki page for more details: https://github.com/ufs-community/UFS_UTILS/wiki/3.-Checking-out-code-and-making-changes

**Comment by GeorgeGayno-NOAA** [comment]
I don't have access to Cheyenne and we don't officially support that machine. So, I trust that your changes are working. 

@JeffBeck-NOAA and @LarissaReames-NOAA do you work on Cheyenne?

**Comment by padhrigmccarthy** [comment]
> I don't have access to Cheyenne and we don't officially support that machine. So, I trust that your changes are working.

@GeorgeGayno-NOAA Yes, we have several people here at RAL/NCAR using these configs on Cheyenne for online-cmaq. Trying to streamline our setup by contributing these configs.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
