### PR TITLE
release/public-v2 chgres_cube: Add regression tests for new regional chgres_cube features

### PR DESCRIPTION
**Pull request by LarissaReames**
This PR adds new regression tests for various combinations of the added regional functionality in chgres_cube.

Drivers for Jet and Hera have been updated. I'll need assistance from someone with access to the other platforms to update those drivers using my new drivers as a guideline. @GeorgeGayno-NOAA has previously offered to help with this. 

My baseline files, along with the corresponding grid and fix files, will need to be put in the same location as the others. I've been informed that the RRFS grids are still being updated as I write this, so these files may not be 100% ready to be copied, but that should change soon. George's help will be needed here as well. The locations of my files are/will be:

Hera: /scratch1/BMC/gsd-fv3/Larissa.Reames/chgres_cube/reg_tests.public.v2/
Jet: /home/Larissa.Reames/hpc-wof1/chgres_cube/reg_tests.public.v2

I will work on modifying these new tests/driver scripts to work with the develop branch in the coming weeks. 

This PR addresses Issue #181

### CODE REVIEW

**Comment by LarissaReames-NOAA** [comment]
Update: The baseline and fix files have been updated with the final versions of the RRFS CONUS grids. Everything should be in place to be copied in to the common location with @GeorgeGayno-NOAA 's files.

**Comment by edwardhartnett** [comment]
I see that these tests are for the public-v2 branch. Is it intended to port them to the develop branch?

**Comment by LarissaReames-NOAA** [comment]
> I see that these tests are for the public-v2 branch. Is it intended to port them to the develop branch?

Yes, that's the plan in the future. For the release, we had to implement a fix for some bad soil type points that I would like to do more robustly before pushing these regression tests to the develop branch.

**Comment by JeffBeck-NOAA** [comment]
Any update on the status of this PR?

**Comment by edwardhartnett** [comment]
Is this PR ready to merge? @GeorgeGayno-NOAA what do you think?

**Comment by JeffBeck-NOAA** [comment]
@GeorgeGayno-NOAA, @edwardhartnett, we need to get this PR merged.  It's been in queue for nearly four months.

**Comment by edwardhartnett** [comment]
I have no objection to merging this PR. We are not applying our documentation and testing requirements to the public-v2 branch. That continues to be developed and managed using legacy methods. So as soon as @GeorgeGayno-NOAA is ready, he may merge this.

**Comment by LarissaReames-NOAA** [comment]
> @LarissaReames-NOAA I can't get your branch to compile on Hera or WCOSS.

So I think the release branch is basically dead now and it would be a lot more work than is necessary to get this PR in on this branch. I propose we just close this PR and move on to a PR to get all of these tests in to the develop branch. The tests themselves won't need to be modified to work with the develop branch, we'll just need to produce the new baseline files.

**Pull request closed without merging**
