### PR TITLE
Create macOS build with Github Action

### PR DESCRIPTION
**Pull request by kgerheiser**

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Awesome!

**Comment by GeorgeGayno-NOAA** [comment]
The 'expected' check is still yellow.  Is something stuck?

**Comment by kgerheiser** [comment]
Yes, I believe you need to go into the repository settings, `branches`, edit `develop`, and uncheck `build` because it the workflow name was changed.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Looks like it works.  Which issue is this being tracked under?

**Comment by kgerheiser** [comment]
It was related to https://github.com/NOAA-EMC/UFS_UTILS/issues/243

**Pull request merged**
