### PR TITLE
removed checks preventing land increments for fractional grids.

### PR DESCRIPTION
**Pull request by ClaraDraper-NOAA**
## DESCRIPTION OF CHANGES: 
Removed two checks that caused global_cycle to report an error and exit in the case that both land increments were being added and fractional grids are used. 

There are no issues adding soil moisture and soil temperature increments in fractional grid mode, so the code can be allowed to proceed. The snow increment code is only for the Noah model at this stage, which is not run the fractional mode anyway.

## TESTS CONDUCTED: 

- [x] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
- [x] Compile branch on Hera using GNU.
- [x] Compile branch in 'Debug' mode on WCOSS2.  Done on Dogwood.
- [x] Run unit tests locally on any Tier 1 machine. Done on Hera.
- [x] Run relevant consistency tests locally on all Tier 1 machine.

## DEPENDENCIES:
none. 

This PR is required for the current global_workflow to be used to be used to perform the soil analysis, in global workflow PR [2263](https://github.com/NOAA-EMC/global-workflow/pull/2263) (still in draft)

## DOCUMENTATION:
none. 

## ISSUE: 
Resolves issue [895](https://github.com/ufs-community/UFS_UTILS/issues/895)

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@ClaraDraper-NOAA I can run the tests on the remaining machines. Thanks for cleaning up the logic.

**Comment by GeorgeGayno-NOAA** [comment]
Ran consistency tests on Orion, Hercules, Jet and Dogwood.  All tests passed as expected.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Looks good.

**Comment by ClaraDraper-NOAA** [comment]
> Ran consistency tests on Orion, Hercules, Jet and Dogwood. All tests passed as expected.

Thanks @GeorgeGayno-NOAA!

**Comment by GeorgeGayno-NOAA** [comment]
@ClaraDraper-NOAA I see that you listed a global workflow PR as a dependency. Can I merge this PR now or should I wait?

**Comment by ClaraDraper-NOAA** [comment]
> @ClaraDraper-NOAA I see that you listed a global workflow PR as a dependency. Can I merge this PR now or should I wait?

Yes, you can merge now. That PR is dependent on this one being merged.

**Pull request merged**
