### PR TITLE
New BNU soil type and VIIRS vegetation type data

### LINKED ISSUE #821: Test new BNU soil type and VIIRS vegetation type data
A new version of the VIIRS vegetation type data was created that removes spurious snow points in warm regions.

`On hera: /scratch2/NCEPDEV/land/data/input_data/vegetation_type/vegetation_type.viirs.v3.igbp.30s.nc`

A new version of the BNU soil type data was created that is compatible with the updated vegetation data. It also includes additional records for the percentage and sand and clay.

`On hera: /scratch2/NCEPDEV/land/data/input_data/soil_type/soil_type.bnu.v3.30s.nc`

Test these new data in `sfc_climo_gen` and regenerate all GFS grids (including new soil color field).

Using 30s data requires more MPI tasks. Because of a quirk in the ESMF library, using too many tasks with coarse input data, such as our substrate temperature data set (2.6x1.5 degree), will cause a library error. This can be resolved by using a higher resolution version (0.5-degree) of this data:

`On hera: /scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS/fix/sfc_climo.test/substrate_temperature.gfs.0.5.nc`

(Code to create the new 0.5-degree data on Hera: `/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/climo_fields_netcdf/sorc/fv3.tbot.gfs.hires.netcdf`

Related to #803.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
A new version of the VIIRS vegetation type data was created that removes spurious snow points in warm regions.
And a new version of the BNU soil type data was created that is compatible with the updated vegetation data. 
It also includes additional records for the percentage and sand and clay.

Only high-res versions of these data (global 30 second) will be baselined. Previous versions of these data included several lower-res versions that reduced the computational resources required to create model grids. Due to a quirk in the ESMF library, increasing the number of MPI tasks for high-res input data can cause a failure when processing low-res data, such as the soil substrate temperature data. Therefore, a resampled (0.5-degree) version of the 2.6x1.5 degree soil substrate data will be baselined as well. 

Update UFS_UTILS to use this new data. 

## TESTS CONDUCTED: 
These tests were done using 76a3b020

- [x] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera and WCOSS2).
- [x] Compile branch on Hera using GNU.
- [x] Compile branch in 'Debug' mode on WCOSS2.
- [x] Run unit tests locally on any Tier 1 machine.  Done on Hera.
- [x] Run relevant consistency tests locally on all Tier 1 machine.

All `grid_gen` consistency tests failed as expected. One source of the failure was the use of the new soil substrate temperature. That data was resampled to higher resolution. Also, the current low-res data has incorrect geo-referencing.  Some comparisons using the new and current substrate data are documented in #821.

The "c96.viirs.bnu" test showed differences beyond the substrate temperature field. That is because it used the new 'v3' soil and vegetation type data. These differences were visually compared against the baseline files and found to be reasonable and expected.

All baseline test data will be updated on all machines after the merge.

## DEPENDENCIES:
The new soil, veg and soil substrate files must be added to the official 'fix' directories on all machines.

- soil_type.bnu.v3.30s.nc
- vegetation_type.viirs.v3.igbp.30s.nc
- substrate_temperature.gfs.0.5.nc

The following snow-contaminated files should be removed:

- soil_type.bnu.30s.nc
- vegetation_type.viirs.igbp.0.03.nc
- vegetation_type.viirs.igbp.0.1.nc
- vegetation_type.viirs.igbp.conus.30s.nc
- vegetation_type.viirs.igbp.0.05.nc
- vegetation_type.viirs.igbp.30s.nc
- vegetation_type.viirs.igbp.nh.30s.nc

## DOCUMENTATION:
Update 'readthedocs' for new input data:
https://georgegayno-noaaufs-utils.readthedocs.io/en/bugfix-bnu_soil/ufs_utils.html#id58

## ISSUE: 
Fixes #821.
Related to #803.

## CONTRIBUTORS: 
@barlage

### CODE REVIEW

**Review by barlage — APPROVED** [review]
Looks good to me.

**Comment by GeorgeGayno-NOAA** [comment]
The list of files that need to be added/removed from the 'fixed' directories is here: https://github.com/ufs-community/UFS_UTILS/issues/821#issuecomment-1729581358

**Comment by GeorgeGayno-NOAA** [comment]
@WalterKolczynski-NOAA or @KateFriedman-NOAA - this PR requires three new files in the `./fix/sfc_climo directory`. These files are:

- /scratch2/NCEPDEV/land/data/input_data/vegetation_type/vegetation_type.viirs.v3.igbp.30s.nc
- /scratch2/NCEPDEV/land/data/input_data/soil_type/soil_type.bnu.v3.30s.nc
- /scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS/fix/sfc_climo.test/substrate_temperature.gfs.0.5.nc

The new 'veg' and 'soil' files replace earlier versions with bad 'glacial' points. Can these be removed or moved to a deprecated directory? These bad files are:

- soil_type.bnu.30s.nc
- vegetation_type.viirs.igbp.0.03.nc
- vegetation_type.viirs.igbp.0.1.nc
- vegetation_type.viirs.igbp.conus.30s.nc
- vegetation_type.viirs.igbp.0.05.nc
- vegetation_type.viirs.igbp.30s.nc
- vegetation_type.viirs.igbp.nh.30s.nc

**Comment by KateFriedman-NOAA** [comment]
> @WalterKolczynski-NOAA or @KateFriedman-NOAA - this PR requires three new files in the `./fix/sfc_climo directory`.

@GeorgeGayno-NOAA can you open a global-workflow ["Fix File Update"](https://github.com/NOAA-EMC/global-workflow/issues/new/choose) issue with these details? We'll make the update. Thanks!

**Pull request merged**
