### PR TITLE
doxygen improvements for chgres_cube.fd/atmosphere.F90 and grib2_util.F90, turn on doxygen cross-references

### LINKED ISSUE #288: Turn on automatic cross references in Doxygen output
As done here:
https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/102#event-4325061477

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #191 

Doxygen improvements. We need to finish up the doxygenation of all the chgres_cube code, as we are in the process of adding testing.

Fixes #288 

Automatic cross-references are nice! I turned them on.

Also edited some CMakeLists.txt files for comments.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA I'll need some help completing these comments...

**Review by lgannoaa — COMMENTED** [review]
I see parameter list under grib2_util.F90 without description on each of them. Is it OK?

**Comment by edwardhartnett** [comment]
@lgannoaa no empty parameter descriptions are not OK. ;-) But I don't know what to put yet. When it's all figured out, the PR will be merged. ;-)

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA can we get some progress on this PR please?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA can we get some progress on this PR please?

I will add my updates to your branch.

**Comment by edwardhartnett** [comment]
OK @GeorgeGayno-NOAA I also need you to approve it in review. It will not let me approve my own PR.

**Comment by GeorgeGayno-NOAA** [comment]
> OK @GeorgeGayno-NOAA I also need you to approve it in review. It will not let me approve my own PR.

I have a minor doxygen updates to add.  Should be done soon.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
It builds without any doxygen warnings or errors (on Dell).  But I don't know why it is not viewing properly for me.  Note how only three subroutines in atmosphere.F90 are listed:
https://georgegayno-noaa.github.io/UFS_UTILS/atmosphere_8F90.html

I can approve, but it would be great if someone else can build it for themselves.

**Comment by lgannoaa** [comment]
I can help. Just let me know...

**Review by lgannoaa — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
> I can help. Just let me know...

You can check out the branch, build the documentation and view it for yourself.

**Pull request merged**
