### PR TITLE
Update doxygen for orog_mask_tools.fd.

### LINKED ISSUE #344: doxygen documentation for sorc/orog_mask_tools.fd
Part of #191

### LINKED ISSUE #408: Clear doxygen warnings from orog_mask_tools.fd
Part of #191.
Part of #344

### LINKED ISSUE #413: Remove unused routines from orog.fd
I am too lazy to add doxygen to 'dead' routines.  

Part of #408.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
Clear all doxygen warnings.  Fill in missing subroutine and function
descriptions.  Define all 'params'.  Remove unused routine 'machine.f90'
from orog.fd program.

Part of #191 
Fixes #344 
Fixes #408 
Fixes #413

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Looks much better! I'm not sure what is happening with the CI, but it's nothing to do with this PR...

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett Can I merge this next?

**Comment by GeorgeGayno-NOAA** [comment]
The CI is showing one doxygen warning.  I did not see this when compiling on Dell.  Will fix.

**Comment by GeorgeGayno-NOAA** [comment]
Ok. Now it is ready to merge.

**Pull request merged**
