### PR TITLE
add address sanitizer run to CI

### LINKED ISSUE #487: Add address sanitizer run to CI
We need to run address sanitizer with CI.

### LINKED ISSUE #489: memory leak in cghres_cube test ftst_sfc_input_data
When adding the address santitizer run I find some problems in ftst_sfc_input_data()

```
(base) ed@mikado:~/UFS_UTILS/b/tests/chgres_cube$ ./ftst_sfc_input_data 
 Starting test of check_soilt subroutine.
 SUCCESS!

=================================================================
==22968==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f0d5a117bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5578c065d3f2 in test_sfc_input_data /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:33
    #2 0x5578c065cbf8 in main /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:8
    #3 0x7f0d58ddecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f0d5a117bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5578c065d061 in test_sfc_input_data /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:31
    #2 0x5578c065cbf8 in main /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:8
    #3 0x7f0d58ddecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f0d5a117bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5578c065d142 in test_sfc_input_data /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:32
    #2 0x5578c065cbf8 in main /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:8
    #3 0x7f0d58ddecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f0d5a117bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5578c065d039 in test_sfc_input_data /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:30
    #2 0x5578c065cbf8 in main /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:8
    #3 0x7f0d58ddecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

Direct leak of 36 byte(s) in 1 object(s) allocated from:
    #0 0x7f0d5a117bc8 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5578c065d01f in test_sfc_input_data /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:29
    #2 0x5578c065cbf8 in main /home/ed/UFS_UTILS/tests/chgres_cube/ftst_sfc_input_data.F90:8
    #3 0x7f0d58ddecb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)

SUMMARY: AddressSanitizer: 540 byte(s) leaked in 5 allocation(s).
```

There are some allocated vars in this test that are not deallocated. I have added the deallocate and will put up a PR shortly.

@LarissaReames-NOAA note that any memory allocated in a test has to be deallocated. In this way we can test for memory leaks in the library.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #487
Fixes #489 

Add address santitizer run to CI.

Also fix memory leak in test.

### CODE REVIEW

**Comment by kgerheiser** [comment]
Is it necessary to add en extra workflow?

**Comment by edwardhartnett** [comment]
No extra workflow may not be needed. I just wanted to get it working first before figuring out how to merge it with the rest of the testing...

**Comment by edwardhartnett** [comment]
@kgerheiser this is working. How shall we integrate this into the existing workflow(s)?

Basically we just need to add the following to get the address santitizer:
`-DCMAKE_Fortran_FLAGS="-fsanitize=address -fno-omit-frame-pointer"`

This will only work on GNU compilers.

Do we want to run this every time? I'm not sure how it will interact with code coverage options.

Should we run it against the develop and the 1.3.0 release of nceplibs? Or just develop?

**Comment by kgerheiser** [comment]
I propose adding `-fsanitize=address -fno-omit-frame-pointer` to the top-level CMakeLists.txt here:

https://github.com/NOAA-EMC/UFS_UTILS/blob/26f1c3d9edb18f882fa9a5922b18ccc93aa9f4d8/CMakeLists.txt#L38

Then, this can be combined with the CI debug build.

**Comment by edwardhartnett** [comment]
@kgerheiser good idea. I'll do as you suggest. Let's merge #490 and then I will change this PR.

**Comment by edwardhartnett** [comment]
@kgerheiser please review and I will merge this one.

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
