### PR TITLE
Allow FVCOM tools to Update Ice Surface Roughness Length

### PR DESCRIPTION
**Pull request by dmwright526**
## DESCRIPTION OF CHANGES: 
Surface roughness was not being updated by FVCOM tools, specifically over ice points.  This created a segfault issue when running the UFS-SRW, specifically with the MYNN surface layer scheme. This problem only appears when points are changed either from water to ice or from ice to water. Now the code will update the variable zorl for cold starts and zorli for warm starts. 

## TESTS CONDUCTED: 
Test was run on Hera using both warm (restart sfc_data.nc) and cold (chgres_cube sfc_data.nc) files.

## DEPENDENCIES:
None.

## DOCUMENTATION:
No update to documentation needed.

## ISSUE: 
Fixes issue mentioned in #602

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
@dmwright526, just wanted to touch base to see if you'd made any additional progress on this work?  Thanks!

**Comment by dmwright526** [comment]
@JeffBeck-NOAA Sorry for the delay in this! I am working on getting a few more variables squared away, including ice thickness (hice) and surface water roughness (zorlw). We just got hice included in output from FVCOM this morning. The restart files I have been working with do not include the variable zorlw, so I am trying to generate a restart file with this variable to do final testing.

**Comment by dmwright526** [comment]
@JeffBeck-NOAA I tested the latest configuration on Hera with warm and cold starts and it works. Let me know if you have any questions.

**Comment by JeffBeck-NOAA** [comment]
@dmwright526 , thanks!  I merged in the latest develop and am waiting on the automated tests to finish.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
