### PR TITLE
doxygen for program_setup.f90

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #191 

More doxygen

### CODE REVIEW

**Review by GeorgeGayno-NOAA — COMMENTED** [review]
Will add variable definitions

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA was the code change you made to this PR intentional?

If so, add an issue describing the code change and refer to it in the comments of this PR.

Let's try to get this completed this week please.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA was the code change you made to this PR intentional?
> 
> If so, add an issue describing the code change and refer to it in the comments of this PR.
> 
> Let's try to get this completed this week please.

Ok.  Is this done in your mind?  Or should I continue to move the variable definitions out of the prolog (as in 27cb893)?

**Comment by edwardhartnett** [comment]
Is there an existing issue for the task: "move the variable definitions out of the prolog"?

If not, please create one.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
I am able to build the doxygen without errors.  But I think it is getting confused with the multiple files named 'program_setup' in ufs_utils:

https://georgegayno-noaa.github.io/UFS_UTILS/index.html

Let's merge.

**Comment by edwardhartnett** [comment]
OK, I'll merge as soon as tests finish...

**Pull request merged**
