### PR TITLE
added documentation build to workflows, turned on doxygen warnings for missing documentation

### PR DESCRIPTION
**Pull request by edwardhartnett**
Add documentation build to CI.

Part of #191

In this PR I turn on documentation build in CI. Also I turn on doxygen warnings if documentation is missing. So in the output of our CI now we can see the warnings. After we have fixed all warnings, we will turn on WARN_AS_ERROR, and then it will cause the CI to fail any change which does not include full doxygen documentation. ;-)

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA perhaps you can review this? Kyle is gone until March... ;-)

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by Hang-Lei-NOAA** [comment]
Yes, I reviewed. Approved.

**Comment by edwardhartnett** [comment]
GitHub did not take your approval seriously...

Maybe I need to add you to the repo? I will check...

**Comment by edwardhartnett** [comment]
OK, thanks @Hang-Lei-NOAA ! I added you to the list and now GitHub will let me merge. ;-)

**Pull request merged**
