### PR TITLE
Update to use EPIC stack on Orion and Hera

### LINKED ISSUE #789: Test new EPIC-maintained hpc-stack on Hera and Orion
The switch the new hpc-stack was already done on Jet. See #771.

For details on how to use the hpc-stack on Hera and Orion, see: https://github.com/ufs-community/ufs-weather-model/issues/1465

The new hpc-stack is already being tested in the global-workflow: https://github.com/NOAA-EMC/global-workflow/issues/1311

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
The build modules for Orion and Hera were updated to use the EPIC-maintained library stack.

## TESTS CONDUCTED: 

Tests were conducted using the branch at 815fc5b (Orion) and 4496d3a (Hera) . For more details, see #789.

- [x] Compile branch on Orion and Hera using Intel.
- [x] Compile branch on Hera using GNU.
- [x] Run unit tests locally on Orion (Intel) and Hera (Intel and GNU). All tests passed
- [x] Run relevant consistency tests locally on Orion and Hera. 
 
Some consistency tests failed. But the differences with the baseline were not significant. For details, see https://github.com/ufs-community/UFS_UTILS/issues/789#issuecomment-1696362246

Baseline files for all failed tests will need to be updated.

## DEPENDENCIES:
Coordinate with global workflow group:
https://github.com/NOAA-EMC/global-workflow/issues/1311

## DOCUMENTATION:
N/A

## ISSUE: 
Fixes #789.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@WalterKolczynski-NOAA can you or someone in the global workflow group test with my branch?

**Comment by WalterKolczynski-NOAA** [comment]
@GeorgeGayno-NOAA I'm on leave today. I'll try to take a look tomorrow unless @KateFriedman-NOAA has the time.

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good. Don't have time to test within global-workflow at the moment but will test when we need to move to this new hash or later. FYI, once the GSI works with intel 2022 I'll be working to move us all to spack-stack. That's on hold for the moment, so it's good to move to this EPIC maintained hpc-stack for now. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
@sanatcumar This PR updated some of the library versions on Hera. When you merge these changes to your #830 branch, your results could change (very slightly).

**Pull request merged**
