### PR TITLE
modify cpld_gridgen as required by new ocnice_prep utility

### LINKED ISSUE #943: create two additional remapping weights using cpld_gridgen for use by ocnice prep; deprecate two weights files and regresssion test dependency
For #942, two additional remapping weights files are required. These are the weights to remap a field from ``Ct`` **back** to the native stagger locations (``Cu``, ``Cv``) on a tripole grid. The file to remap from ``Ct`` back to ``Bu`` for all resolutions was added in PR #922, but the other two files were forgotten. However, the ``Ct.to.Bu`` file does not need to be generated for the 1/4 deg case and can be removed.

In addition, two weights files are currently generated for use by the NCL routine previously used to generate ICE initial conditions and are now deprecated. These files were generated only for non-1/4deg cases and required that the regresssion tests for the ``cpld_gridgen`` had a dependency on first running the 1/4deg case prior to any other the other cases. For the 1deg case, the files generated were named

```
tripole.mx025.Ct.to.mx100.Ct.bilinear.nc
tripole.mx025.Ct.to.mx100.Ct.neareststod.nc
```
and similar names for the other non-1/4deg tripole resolutions (``mx050``, ``mx100``, ``mx500``).

The ``cpld_gridgen`` code needs updating to remove the deprecated weight generation, add the generation of the two new weights and update the ``rt.sh`` and ``rt.conf`` to remove the dependency on the 1/4deg cases.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## DESCRIPTION OF CHANGES: 
Adds two required weights to map fields from center grid points (``Ct``) back to their native stagger locations for MOM6. Also deprecates two weights currently being generated for previous NCL based creation of ICs for CICE and removes the associated regression test dependency.

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [ ] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
- [ ] Compile branch on Hera using GNU.
- [ ] Compile branch in 'Debug' mode on WCOSS2.
- [ ] Run unit tests locally on any Tier 1 machine.
- [ ] Run relevant consistency tests locally on all Tier 1 machines.

Optional test.

- [ ] Run full set of chgres_cube consistency tests on Hera.

Describe any additional tests performed.

Baselines are expected to fail because of the following missing files. All failures are expected. 
 - the Ct.mx025_SCRIP files are missing because the dependency has been removed. 
 - the Ct->Bu file for mx025 is removed because that mapping is never required. 
 - the tripole:tripole files are removed because NCL method using those weights is deprecated.
```
28:Comparing tripole.mx025.Ct.to.Bu.bilinear.nc........MISSING file
53:Comparing Ct.mx025_SCRIP.nc........MISSING file
65:Comparing tripole.mx025.Ct.to.mx050.Ct.bilinear.nc........MISSING file
66:Comparing tripole.mx025.Ct.to.mx050.Ct.neareststod.nc........MISSING file
91:Comparing Ct.mx025_SCRIP.nc........MISSING file
102:Comparing tripole.mx025.Ct.to.mx100.Ct.bilinear.nc........MISSING file
103:Comparing tripole.mx025.Ct.to.mx100.Ct.neareststod.nc........MISSING file
127:Comparing Ct.mx025_SCRIP.nc........MISSING file
137:Comparing tripole.mx025.Ct.to.mx500.Ct.bilinear.nc........MISSING file
138:Comparing tripole.mx025.Ct.to.mx500.Ct.neareststod.nc........MISSING file
```
## DOCUMENTATION:

The documentation requires minor changes to remove references to the deprecated NCL method. 

## ISSUE: 

- fixes #943

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@GeorgeGayno-NOAA I've spent way too much time today trying to figure out how to add a figure to the documentation for ``cpld_gridgen``. I have the figure as a png file in docs/_static and I'm trying to reference in ``docs/cpld_gridgen.md`` using

```
.. _figure_reference:

.. figure:: _static/murray.png
```
The documentation builds, but I don't see the figure when I look at the documentation in my gh-pages branch.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I've spent way too much time today trying to figure out how to add a figure to the documentation for `cpld_gridgen`. I have the figure as a png file in docs/_static and I'm trying to reference in `docs/cpld_gridgen.md` using
> 
> ```
> .. _figure_reference:
> 
> .. figure:: _static/murray.png
> ```
> 
> The documentation builds, but I don't see the figure when I look at the documentation in my gh-pages branch.

I will take a look.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I've spent way too much time today trying to figure out how to add a figure to the documentation for `cpld_gridgen`. I have the figure as a png file in docs/_static and I'm trying to reference in `docs/cpld_gridgen.md` using
> 
> ```
> .. _figure_reference:
> 
> .. figure:: _static/murray.png
> ```
> 
> The documentation builds, but I don't see the figure when I look at the documentation in my gh-pages branch.

That looks like 'readthedocs' syntax. I don't know if this is what we want:
https://github.github.com/gfm/#images
https://www.seancdavis.com/posts/three-ways-to-add-image-to-github-readme/

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I've spent way too much time today trying to figure out how to add a figure to the documentation for `cpld_gridgen`. I have the figure as a png file in docs/_static and I'm trying to reference in `docs/cpld_gridgen.md` using
> 
> ```
> .. _figure_reference:
> 
> .. figure:: _static/murray.png
> ```
> 
> The documentation builds, but I don't see the figure when I look at the documentation in my gh-pages branch.

After a lot of trial and error, I think it is working. I modified two files:

```
--- a/sorc/cpld_gridgen.fd/docs/Doxyfile.in
+++ b/sorc/cpld_gridgen.fd/docs/Doxyfile.in
@@ -960,7 +960,8 @@ EXAMPLE_RECURSIVE      = NO
 # that contain images that are to be included in the documentation (see the
 # \image command).

-IMAGE_PATH             =
+IMAGE_PATH             =@abs_top_srcdir@/sorc/cpld_gridgen.fd/docs/_static
```

```
--- a/sorc/cpld_gridgen.fd/docs/cpld_gridgen.md
+++ b/sorc/cpld_gridgen.fd/docs/cpld_gridgen.md
@@ -191,9 +191,7 @@ domain of the ocean and ice for the global models is always the
 tripole grid, which is characterized by three "poles", one in the
 southern hemisphere and two in the north, both over land.

-.. _figure_reference:
-
-.. figure:: _static/murray.png
+\image html murray.png

```

**Comment by DeniseWorthen** [comment]
@GeorgeGayno-NOAA Thanks a lot for figuring it out. Let me add those changes and see if I can reproduce your method.

**Comment by DeniseWorthen** [comment]
This PR has been merged into #942. Closing.

Note: The current ``cpld_gridgen`` baselines will contain additional files which will no longer be produced after #942 is merged. This should be kept in mind for the next PR which would update the ``cpld_gridgen`` baseline.

**Pull request closed without merging**
