### PR TITLE
Test for chgres_cube, write_data.F90, subroutine write_fv3_atm_header_netcdf()

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #308.

Adding test for chgres_cube, write_data.F90, subroutine write_fv3_atm_header_netcdf().

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA can I have one of the output files from this subroutine?

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA can I have one of the output files from this subroutine?

**Comment by GeorgeGayno-NOAA** [comment]
On Hera, you can find one under any of the subdirectories here: /scratch1/NCEPDEV/da/George.Gayno/noscrub/reg_tests/chgres_cube/baseline_data

**Comment by GeorgeGayno-NOAA** [comment]
> Currently I don't have access to hera due to my credentials expiring, and renewal being delayed by my transfer from GSL to EMC. ;-) So sorry, I can't get at this data at the moment.

What machine do you have access to?

**Comment by edwardhartnett** [comment]
This will have to wait until the end of the Summer, as I am wrapped up in spack work for the foreseeable future.

**Pull request closed without merging**
