### PR TITLE
Add Findwgrib2.cmake

### LINKED ISSUE #577: Use FindWgrib2.cmake
The CMake build of wgrib2 was removed from hpc-stack. Should use FindWgrib2.cmake to find wgrib2 now.

And the target changes to `wgrib2::wgrib2` instead of `wgrib2::wgrib2_lib` and `wgrib2::wgrib2_api` here:

https://github.com/NOAA-EMC/UFS_UTILS/blob/develop/sorc/chgres_cube.fd/CMakeLists.txt

### PR DESCRIPTION
**Pull request by kgerheiser**
Fix #577

### CODE REVIEW

**Comment by kgerheiser** [comment]
Everything is good now. 

Turns out the wgrib2 compiled in our Actions couldn't be run because the libraries we built it with weren't in the LD_LIBRARY_PATH. So, I turned everything into static libraries. 

Then, the cache was pulling old builds and there's no way to clear it, so I had to change the cache key by appending a number.

**Comment by kgerheiser** [comment]
Ran the regression tests through all of the machines, and the only problem is WCOSS-Cray because the wgrib2 exectuable doesn't work, which is used to retrieve the version number. WIll work on getting that fixed.

**Comment by kgerheiser** [comment]
wgrib2 has been fixed on WCOSS Cray, and regression tests passed.

**Comment by kgerheiser** [comment]
Ready for review @GeorgeGayno-NOAA 

I successfully ran the chgres_cube regression tests on each machine. 

Updated to the 'v1.3.0` location of NCEPLIBS on WCOSS-Cray for a fixed wgrib2, which @Hang-Lei-NOAA keeps up-to-date.

**Comment by GeorgeGayno-NOAA** [comment]
> Ready for review @GeorgeGayno-NOAA
> 
> I successfully ran the chgres_cube regression tests on each machine.
> 
> Updated to the 'v1.3.0` location of NCEPLIBS on WCOSS-Cray for a fixed wgrib2, which @Hang-Lei-NOAA keeps up-to-date.

Thanks, @kgerheiser Will review now.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser I tried your updated package find with my WCOSS2 branch (4468002). I load 'wgrib2/2.0.8'. The package find did not return the path/library.  Here is the log output from the build.
```
-- Found g2: /apps/ops/prod/libs/intel/19.1.3.304/g2/3.4.1/lib/libg2_4.a (found version "3.4.0")
-- Found wgrib2: ; (found suitable version "2.0.8", minimum required is "2.0.8")
-- Found sigio: /apps/ops/prod/libs/intel/19.1.3.304/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_LOCATION not set for imported target "wgrib2::wgrib2"
  configuration "Release".
```

I then pointed to 'wgrib2/2.0.8_mpi'. It got past the configure step, but fails during the compilation.

Otherwise, it builds on all the other supported machines.

Someday, I will rip out this wgrib2 library and replace it with our G2 library.

**Comment by kgerheiser** [comment]
Darn, I didn't try WCOSS2. Let me see what's wrong.

**Comment by kgerheiser** [comment]
Just a simple typo. Builds on WCOSS2 now.

**Comment by GeorgeGayno-NOAA** [comment]
> Just a simple typo. Builds on WCOSS2 now.

Thanks. I will try it now.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser I just tried compiling c1316da on Surge. I get this error:

```
CMake Error at cmake/Findwgrib2.cmake:35 (string):
  string begin index: 1 is out of range 0 - 0
Call Stack (most recent call first):
  CMakeLists.txt:64 (find_package)
```

But it does seem to find wgrib2:

`-- Found wgrib2: /usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/wgrib2/wgrib2-2.0.8/lib64/libwgrib2_api.a;/usrx/local/nceplibs/NCEPLIBS/cmake/install/NCEPLIBS-v1.3.0/wgrib2/wgrib2-2.0.8/lib64/libwgrib2.a (Required is at least version "2.0.8")`

On Luna, it compiles with no problems. Very odd.

**Comment by kgerheiser** [comment]
Ah, @Hang-Lei-NOAA can you make sure the library installations match on the WCOSS-Cray systems.

**Comment by kgerheiser** [comment]
The build on Surge has been fixed

**Comment by GeorgeGayno-NOAA** [comment]
> The build on Surge has been fixed

It works! Thanks.

**Comment by GeorgeGayno-NOAA** [comment]
Tested the branch at c1316da on Hera, Orion, Jet, Luna and Venus. Compiled successfully on all machines. And the chgres_cube regression tests all passed. Ready to merge.

**Comment by GeorgeGayno-NOAA** [comment]
I also tried the updated package find with my WCOSS2 porting branch at 4468002. It is working.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
@kgerheiser Thanks for your hard work on this.

**Pull request merged**
