### PR TITLE
Add ip v5 support

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
## DESCRIPTION OF CHANGES: 
This PR adds support for ip v5 (which subsumes sp library), while leaving support for older ip+sp combo.

## TESTS CONDUCTED:
The following were all completed using ip v5 (no separate sp library), with the exception of the test on Hera described below the checklist.
- [x] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
 - orion: /home/arichert/spack-stack-ufsutils-ip5/UFS_UTILS/build
 - hera: /scratch1/NCEPDEV/nems/Alexander.Richert/spack-stack-ufsutils-ip5/envs/test/UFS_UTILS/build
 - hercules: /work/noaa/nems/arichert/spack-stack-ufsutils-ip5/UFS_UTILS/build
 - jet: /home/Alexander.Richert/spack-stack-ufsutils-ip5/UFS_UTILS/build (ran MPI tests manually; all passed)
 - acorn: /lfs/h1/emc/nceplibs/noscrub/alexander.richert/spack-stack-ufsutils-ip5/UFS_UTILS/build
- [x] Compile branch on Hera using GNU. /scratch1/NCEPDEV/nems/Alexander.Richert/spack-stack-ufsutils-ip5/envs/test/UFS_UTILS/build_gcc
- [x] Compile branch in 'Debug' mode on WCOSS2. /lfs/h1/emc/nceplibs/noscrub/alexander.richert/spack-stack-ufsutils-ip5/UFS_UTILS/build_debug
- [x] Run unit tests locally on any Tier 1 machine.
- [x] Run relevant consistency tests locally on all Tier 1 machine. Done using c8cb906. All tests passed as expected.

Also successfully compiled & ran ctest suite on Hera with ip 4 (+sp) to ensure all the logic still supports the existing ip+sp combo: /scratch1/NCEPDEV/nems/Alexander.Richert/spack-stack-ufsutils-ip5/envs/test/UFS_UTILS/build_ip4

## DEPENDENCIES:
none

## DOCUMENTATION:
n/a

## ISSUE: 
Related to https://github.com/JCSDA/spack-stack/issues/1020

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
@GeorgeGayno-NOAA could we do a release with these changes as soon as possible? I'd really like to get ip v5 into the next spack-stack release and this is the last piece of the puzzle.

**Comment by GeorgeGayno-NOAA** [comment]
@AlexanderRichert-NOAA - the consistency tests are located under `./reg_tests`. For this PR, the `chgres_cube`, `global_cycle`, `grid_gen`, `snow2mdl` and `weight_gen` tests will need to be run. Can you run them on Hera? You are not changing the version of IP in this PR, so I would not expect differences.

**Comment by GeorgeGayno-NOAA** [comment]
> @AlexanderRichert-NOAA - the consistency tests are located under `./reg_tests`. For this PR, the `chgres_cube`, `global_cycle`, `grid_gen`, `snow2mdl` and `weight_gen` tests will need to be run. Can you run them on Hera? You are not changing the version of IP in this PR, so I would not expect differences.

I ran these tests on Hera/Orion/Cactus/Hercules using c8cb906. They all passed as expected. I will do Jet next.

**Comment by GeorgeGayno-NOAA** [comment]
> > @AlexanderRichert-NOAA - the consistency tests are located under `./reg_tests`. For this PR, the `chgres_cube`, `global_cycle`, `grid_gen`, `snow2mdl` and `weight_gen` tests will need to be run. Can you run them on Hera? You are not changing the version of IP in this PR, so I would not expect differences.
> 
> I ran these tests on Hera/Orion/Cactus/Hercules using [c8cb906](https://github.com/ufs-community/UFS_UTILS/commit/c8cb90670bd878e9907fb20c5e9da8d76201b584). They all passed as expected. I will do Jet next.

They also passed on Jet.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
