### PR TITLE
VIIRS-based vegetation type data

### LINKED ISSUE #216: Incorporate NESDIS VIIRS-based surface data
NESDIS will deliver new VIIRS-based surface type (vegetation type) data. These data will have the same classification scheme (17-class IGBP + 3 EMC-suggested tundra classes). The data projection will be on the same grid/projection (30" global lat-lon) as the current MODIS-based data.

Incorporate this data into the grid generation process.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
Updates so users can optionally use the new VIIRS-based vegetation
type data provided by NESDIS.

Add unit test for `sfc_climo_gen` that checks the processing of this
data.

Add consistency test that uses this new data.

Add a utility script so users can run the `sfc_climo_gen` step as stand-alone
using pre-existing 'grid' and 'orography' files.

Fixes #216

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
The regression tests were run (using 8043a10) on Hera, Jet, Orion, WCOSS-Cray and WCOSS-Dell. The tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
Two tests are failing because of memory leaks in an ESMF routine. I have no idea how to fix it.

**Comment by LarissaReames-NOAA** [comment]
> Two tests are failing because of memory leaks in an ESMF routine. I have no idea how to fix it.

I get similar memory leak issues in my soiltype_fix PR, but not in my nst_land_fill PR. The latter uses a lot of ESMF commands (creating a grid, FieldGet, FieldGather, etc.), but it does not perform any regridding, while the soiltype_fix PR does, as does this PR. Based on that, my guess is the leaks are associated with RegridStore or Regrid.

**Comment by LarissaReames-NOAA** [comment]
I've got a test working in a [branch](https://github.com/LarissaReames-NOAA/UFS_UTILS/tree/feature/test_esmf_memory) on my fork that shows the failure of both soiltype_fix test and the pared down, ESMF-only esmf_bug test. Feel free to look it over to make sure there's not something missing, but it certainly appears that the memory leak is internal to ESMF.

**Comment by edwardhartnett** [comment]
@LarissaReames-NOAA can you send your ESMF test program to esmf_support@ucar.edu and ask them about it?

**Comment by LarissaReames-NOAA** [comment]
> @LarissaReames-NOAA can you send your ESMF test program to [esmf_support@ucar.edu](mailto:esmf_support@ucar.edu) and ask them about it?

Done. I forgot to cc you guys (whoops) but I'll make sure to forward whatever answer I get from them.

**Comment by edwardhartnett** [comment]
OK, now we need to figure out how to tell address santizer to ignore ESMF...

**Comment by LarissaReames-NOAA** [comment]
> OK, now we need to figure out how to tell address santizer to ignore ESMF...

I found this website that specifically lays out how to ignore leaks from external libraries: https://clang.llvm.org/docs/AddressSanitizer.html . It looks like we can use language like `ASAN_OPTIONS=suppressions=MyASan.supp` to point to a file that has a line like `interceptor_via_lib:ESMF` .  The [Github page on the address sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags) mentions this suppressions option as well.

**Comment by LarissaReames-NOAA** [comment]
Update: I was able to suppress errors this way at runtime: 
`export suppressions=LSanSuppress.supp`
Content of build/tests/chgres_cube/LSanSuppress.supp:
```
leak:ESMCI
leak:esmf
```

This allowed my test code that I sent on to ESMF support to pass. I'm still getting other leaks in my surface_interp test, however, that don't have those strings in their symbolized stack trace:
```
==287854==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 77 byte(s) in 3 object(s) allocated from:
    #0 0x2b931dc8ad3f in operator new(unsigned long) /tmp/Role.Apps/spack-stage/spack-stage-gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/spack-src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x928b33 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/scratch1/BMC/gsd-fv3/Larissa.Reames/UFS_UTILS_develop/build/tests/chgres_cube/ftst_surface_interp+0x928b33)

Indirect leak of 36 byte(s) in 3 object(s) allocated from:
    #0 0x2b931dc8ad3f in operator new(unsigned long) /tmp/Role.Apps/spack-stage/spack-stage-gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/spack-src/libsanitizer/asan/asan_new_delete.cc:104
    #1 0x953bfd in std::vector<int, std::allocator<int> >::_M_default_append(unsigned long) (/scratch1/BMC/gsd-fv3/Larissa.Reames/UFS_UTILS_develop/build/tests/chgres_cube/ftst_surface_interp+0x953bfd)
```

Where these are coming from is less straightforward, so it's difficult to decide exactly which string to suppress.

**Comment by GeorgeGayno-NOAA** [comment]
> Update: I was able to suppress errors this way at runtime:
> `export suppressions=LSanSuppress.supp`
> Content of build/tests/chgres_cube/LSanSuppress.supp:
> 
> ```
> leak:ESMCI
> leak:esmf
> ```
> 

I just tried your solution, but it is not working for me. Can I see your branch?

> This allowed my test code that I sent on to ESMF support to pass. I'm still getting other leaks in my surface_interp test, however, that don't have those strings in their symbolized stack trace:
> 
> ```
> ==287854==ERROR: LeakSanitizer: detected memory leaks
> 
> Indirect leak of 77 byte(s) in 3 object(s) allocated from:
>     #0 0x2b931dc8ad3f in operator new(unsigned long) /tmp/Role.Apps/spack-stage/spack-stage-gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/spack-src/libsanitizer/asan/asan_new_delete.cc:104
>     #1 0x928b33 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) (/scratch1/BMC/gsd-fv3/Larissa.Reames/UFS_UTILS_develop/build/tests/chgres_cube/ftst_surface_interp+0x928b33)
> 
> Indirect leak of 36 byte(s) in 3 object(s) allocated from:
>     #0 0x2b931dc8ad3f in operator new(unsigned long) /tmp/Role.Apps/spack-stage/spack-stage-gcc-9.2.0-wqdecm4rkyyhejagxwmnabt6lscgm45d/spack-src/libsanitizer/asan/asan_new_delete.cc:104
>     #1 0x953bfd in std::vector<int, std::allocator<int> >::_M_default_append(unsigned long) (/scratch1/BMC/gsd-fv3/Larissa.Reames/UFS_UTILS_develop/build/tests/chgres_cube/ftst_surface_interp+0x953bfd)
> ```
> 
> Where these are coming from is less straightforward, so it's difficult to decide exactly which string to suppress.

**Comment by LarissaReames-NOAA** [comment]
Ah, yes it looks like I mistyped an important part. Instead of 
`export suppressions=LSanSuppress.supp`
it should be 
`export LSAN_OPTIONS=suppressions=LSanSuppress.supp`

Make sure that file is in build/tests/chgres_cube unless you're using an explicit full path to a file. I was able to get this to work on Hera by compiling with gnu, turning on the Debug CMAKE_BUILD_TYPE, and using these LSAN options. 

@edwardhartnett Do you know how we could get this environmental variable used by the Github testing/actions interface? The `LSanSuppress.supp` file could be included in the repository, but I don't know how to get that variable set without explicitly setting it at the command line.

**Comment by edwardhartnett** [comment]
@LarissaReames-NOAA you can set environment vars in the github workflow file:
https://github.com/NOAA-EMC/UFS_UTILS/blob/develop/.github/workflows/debug-docs-test_coverage.yml

Line 109 sets the PATH environment var. Insert a line just below to set the var you want to set. 

Make sure you git add the suppression file. It should probably be in the test/chgres_cube directory.

**Comment by GeorgeGayno-NOAA** [comment]
> Ah, yes it looks like I mistyped an important part. Instead of
> `export suppressions=LSanSuppress.supp`
> it should be
> `export LSAN_OPTIONS=suppressions=LSanSuppress.supp`
> 
> Make sure that file is in build/tests/chgres_cube unless you're using an explicit full path to a file. I was able to get this to work on Hera by compiling with gnu, turning on the Debug CMAKE_BUILD_TYPE, and using these LSAN options.
> 
> @edwardhartnett Do you know how we could get this environmental variable used by the Github testing/actions interface? The `LSanSuppress.supp` file could be included in the repository, but I don't know how to get that variable set without explicitly setting it at the command line.

Thanks, it is working now.

**Comment by GeorgeGayno-NOAA** [comment]
@HelinWei-NOAA and @kgerheiser I would like to get this merged. Can you please review?

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA / @LarissaReames-NOAA  Do either of you use the grid creation scripts? I am looking for someone to review this PR.

**Comment by GeorgeGayno-NOAA** [comment]
@barlage Who on the land team would be best to review this PR? @HelinWei-NOAA ?

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA / @LarissaReames-NOAA Do either of you use the grid creation scripts? I am looking for someone to review this PR.

@GeorgeGayno-NOAA, sorry, I only use the grid generation script that is in the SRW App workflow.  I did take a quick look through and didn't see anything that looked obviously incorrect.  Hopefully someone from the land team can review this PR as well.

**Review by HelinWei-NOAA — APPROVED** [review]
For consistency, should we start the name of  the other source of vegetation type data  with modis? For example replace igbp.0.05 by modis.igbp.0.05 to be comparable with viirs.igbp.0.05.

**Review by HelinWei-NOAA — APPROVED** [review]

**Comment by HelinWei-NOAA** [comment]
I should do this review. Sorry for the delay.

**Comment by GeorgeGayno-NOAA** [comment]
> For consistency, should we start the name of the other source of vegetation type data with modis? For example replace igbp.0.05 by modis.igbp.0.05 to be comparable with viirs.igbp.0.05.

Good idea. I will ask @KateFriedman-NOAA to update.

@KateFriedman-NOAA Can you rename all the "vegetation_type.igbp" files (in ./fix_sfc_climo) to "vegetation_type.modis.igbp". And can you create a link to the old file name for anyone using an old tag of UFS_UTILS. Thanks.

**Review by HelinWei-NOAA — APPROVED** [review]
All changes look good to me.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Done, I made the change to the fix set on Venus. Please confirm this looks correct and I'll rsync it to the other platforms. I'll also make the same change in the newer fix_NEW set but won't make the symlinks (that sound ok for that set?).

```
.../emc.glopara/git/fv3gfs/fix/fix_sfc_climo> pwd
/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix/fix_sfc_climo
[ =0 14:38:54 1017 emc.glopara@v72a1 ]
.../emc.glopara/git/fv3gfs/fix/fix_sfc_climo> ll vegetation_type.* | grep -v viirs
lrwxrwxrwx 1 emc.glopara global          34 Jun 24 14:38 vegetation_type.igbp.0.03.nc -> vegetation_type.modis.igbp.0.03.nc
lrwxrwxrwx 1 emc.glopara global          34 Jun 24 14:38 vegetation_type.igbp.0.05.nc -> vegetation_type.modis.igbp.0.05.nc
lrwxrwxrwx 1 emc.glopara global          40 Jun 24 14:38 vegetation_type.igbp.conus.0.01.nc -> vegetation_type.modis.igbp.conus.0.01.nc
-rwxr-xr-x 1 emc.glopara global   288299990 Mar 11  2019 vegetation_type.modis.igbp.0.03.nc
-rwxr-xr-x 1 emc.glopara global   103864790 Dec 12  2018 vegetation_type.modis.igbp.0.05.nc
-rwxr-xr-x 1 emc.glopara global   240764404 Mar  8  2019 vegetation_type.modis.igbp.conus.0.01.nc
```

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Done, I made the change to the fix set on Venus. Please confirm this looks correct and I'll rsync it to the other platforms. I'll also make the same change in the newer fix_NEW set but won't make the symlinks (that sound ok for that set?).
> 
> ```
> .../emc.glopara/git/fv3gfs/fix/fix_sfc_climo> pwd
> /gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix/fix_sfc_climo
> [ =0 14:38:54 1017 emc.glopara@v72a1 ]
> .../emc.glopara/git/fv3gfs/fix/fix_sfc_climo> ll vegetation_type.* | grep -v viirs
> lrwxrwxrwx 1 emc.glopara global          34 Jun 24 14:38 vegetation_type.igbp.0.03.nc -> vegetation_type.modis.igbp.0.03.nc
> lrwxrwxrwx 1 emc.glopara global          34 Jun 24 14:38 vegetation_type.igbp.0.05.nc -> vegetation_type.modis.igbp.0.05.nc
> lrwxrwxrwx 1 emc.glopara global          40 Jun 24 14:38 vegetation_type.igbp.conus.0.01.nc -> vegetation_type.modis.igbp.conus.0.01.nc
> -rwxr-xr-x 1 emc.glopara global   288299990 Mar 11  2019 vegetation_type.modis.igbp.0.03.nc
> -rwxr-xr-x 1 emc.glopara global   103864790 Dec 12  2018 vegetation_type.modis.igbp.0.05.nc
> -rwxr-xr-x 1 emc.glopara global   240764404 Mar  8  2019 vegetation_type.modis.igbp.conus.0.01.nc
> ```

Yes. That is what I want. Thanks.

**Comment by KateFriedman-NOAA** [comment]
> Yes. That is what I want. Thanks.

Ok great, thanks for confirming! I have rsync'd this change to the other "fix" copies on supported platforms. I also renamed the same files in the newer fix_NEW but did not include the symlinks to the old names in that copy. As a reminder, fix_NEW is where I am restructuring the fix set into what we will use in the future. The fix_NEW set will replace the current development fix set at some point.

**Comment by GeorgeGayno-NOAA** [comment]
> > @GeorgeGayno-NOAA Done, I made the change to the fix set on Venus. Please confirm this looks correct and I'll rsync it to the other platforms. I'll also make the same change in the newer fix_NEW set but won't make the symlinks (that sound ok for that set?).
> > ```
> > .../emc.glopara/git/fv3gfs/fix/fix_sfc_climo> pwd
> > /gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix/fix_sfc_climo
> > [ =0 14:38:54 1017 emc.glopara@v72a1 ]
> > .../emc.glopara/git/fv3gfs/fix/fix_sfc_climo> ll vegetation_type.* | grep -v viirs
> > lrwxrwxrwx 1 emc.glopara global          34 Jun 24 14:38 vegetation_type.igbp.0.03.nc -> vegetation_type.modis.igbp.0.03.nc
> > lrwxrwxrwx 1 emc.glopara global          34 Jun 24 14:38 vegetation_type.igbp.0.05.nc -> vegetation_type.modis.igbp.0.05.nc
> > lrwxrwxrwx 1 emc.glopara global          40 Jun 24 14:38 vegetation_type.igbp.conus.0.01.nc -> vegetation_type.modis.igbp.conus.0.01.nc
> > -rwxr-xr-x 1 emc.glopara global   288299990 Mar 11  2019 vegetation_type.modis.igbp.0.03.nc
> > -rwxr-xr-x 1 emc.glopara global   103864790 Dec 12  2018 vegetation_type.modis.igbp.0.05.nc
> > -rwxr-xr-x 1 emc.glopara global   240764404 Mar  8  2019 vegetation_type.modis.igbp.conus.0.01.nc
> > ```
> 
> Yes. That is what I want. Thanks.

@KateFriedman-NOAA Can you please update Orion.

**Comment by KateFriedman-NOAA** [comment]
> Can you please update Orion.

Updated! :)

**Comment by GeorgeGayno-NOAA** [comment]
> > Can you please update Orion.
> 
> Updated! :)

Thanks. We have too many machines to support. :(

**Comment by KateFriedman-NOAA** [comment]
> We have too many machines to support. :(

We do indeed! It's mainly annoying when we don't have group accounts (e.g. Orion) so I can't push to all of the supported machines emc.glopara[glopara] account spaces at the same time and have to remember to manually update in my personal account on Orion (like this time). I've been told that group accounts are coming to Orion finally so hopefully this will get easier! *fingers crossed*

**Pull request merged**
