### PR TITLE
Add Github Action on macOS and clang

### LINKED ISSUE #756: MacOS CI build breaking
Well the MacOS CI builds all broke a little while ago.

The main problem seems to be the brew update command. This command updates all the software (apparently) on the MacOS. It's slow and unnecessary, as we use very little - just compilers and a few tools. Somehow the brew update command is broken on macos-latest in GitHub. Something fails to do with PHP. However, removing the brew update command works.

Meanwhile, another of the workflows was building mpich/openmpi. Actually we don't need to build these, we can just install them with package management tools apt-get on Linux and brew on MacOS. Something about the build of mpich broke on the MacOS. Something to do with the new compilers I think. Rather than fix that, I just switch to using package management installs.

Currently there is a compile problem for the code, which I'm asking George about, and an ESMF build problem, which I am asking ESMF about.

### PR DESCRIPTION
**Pull request by aerorahul**
## DESCRIPTION OF CHANGES: 
This repository is missing a CI for macOS.

This PR:
- adds a github action for macOS with clang.
- uses v3 of `cache` in the workflows.
- Removes old and broken workflows.

## TESTS CONDUCTED: 
The changes in this PR have no impact on current configuration on on-prem systems.  No tests were conducted on HPC platforms.

Additional github action for macOS + clang was added.
The software dependencies are built with spack and are cached.

ufs-utils fails to build on macOS which highlights that the ufs-utils is not portable to macOS platform. This
PR does not fix this problem, it only baselines a workflow for macOS. I

## DEPENDENCIES:
None

## DOCUMENTATION:
None

## ISSUE: 
Fixes #756 

## CONTRIBUTORS: 
None

### CODE REVIEW

**Comment by aerorahul** [comment]
@GeorgeGayno-NOAA @edwardhartnett 
The Clang macOS Build and Test / ufs_utils step of https://github.com/ufs-community/UFS_UTILS/actions/runs/5883650102/job/15958702123?pr=842 is expected to fail.
UFS-utils does not build on macOS.

I suggest disabling this workflow until someone fixes ufs-utils to be macOS compatible.

**Comment by edwardhartnett** [comment]
Seems like the errors are caused by a c99 flag. Can that be turned off?

```
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], 0.0, u2, inbound, p1_1[0], p1_1[1], p1_1[2]);
            ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: note: did you mean 'isIntersect'?
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/mosaic_util.h:78:5: note: 'isIntersect' declared here
int isIntersect(struct Node node);
    ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1605:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], u1, u2, inbound, p1_0[0], p1_0[1], p1_0[2]);
            ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2118:8: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
```

**Review by edwardhartnett — APPROVED** [review]
Thanks for getting the CI system working again!!

**Comment by aerorahul** [comment]
> Seems like the errors are caused by a c99 flag. Can that be turned off?
> 
> ```
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], 0.0, u2, inbound, p1_1[0], p1_1[1], p1_1[2]);
>             ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: note: did you mean 'isIntersect'?
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/mosaic_util.h:78:5: note: 'isIntersect' declared here
> int isIntersect(struct Node node);
>     ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1605:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], u1, u2, inbound, p1_0[0], p1_0[1], p1_0[2]);
>             ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2118:8: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
> ```

@edwardhartnett Yes.  I tried that, but there are more (other) errors and I don't want to capture enabling CI on macOS and fixing errors on macOS in the same PR.  It is also a rabbit-hole I do not wish to enter.  I will leave that to someone else.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
