### PR TITLE
More testing of chgres_cube.fd/program_setup.F90, with different config files

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #296 

More testing for program_files.F90.

@GeorgeGayno-NOAA the FV3 tiled warm restart config file gets an error when read as a namelist. (That part of the test is commented out, starting like 79 of tests/chgres_cube/ftst_program_setup.F90).

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
I ran all the tests manually and they all fail with 'stop 4'.  It is not just the warm restart test.

**Comment by edwardhartnett** [comment]
Did you rerun cmake?

stop 4 means it did not find the file fort.41. How are you running the test?

What I do is build in subdirectory b. Then I can cd to b/tests/chgres_cube and run the program with ./ftst_program_setup. Cmake should already have populated that subdirectory with all the config files needed for the test.

**Comment by GeorgeGayno-NOAA** [comment]
> Did you rerun cmake?
> 
> stop 4 means it did not find the file fort.41. How are you running the test?
> 
> What I do is build in subdirectory b. Then I can cd to b/tests/chgres_cube and run the program with ./ftst_program_setup. Cmake should already have populated that subdirectory with all the config files needed for the test.

Yes.  That is what I am doing.  I see you did a merge while I was eating lunch.   The grib2 test now works.  Let me try the others.

**Comment by GeorgeGayno-NOAA** [comment]
Ok.   Here is what I see.  It is failing at this line:

 ` ! if (cycle_mon .ne. 10 .or. cycle_day .ne. 3 .or. cycle_hour .ne. 0) stop 54`

The config_fv3_tiled_warm_restart.nml has this for those entries:

  ```
cycle_mon=07
  cycle_day=06
  cycle_hour=12
```

Other of the 'if' tests look wrong as well.

**Comment by edwardhartnett** [comment]
Stand by I will re-examine to see if I have any idea what I am talking about...

**Comment by edwardhartnett** [comment]
OK, the part that is failing is commented out in this test.

I suggest we merge this PR, and circle back around to figure out what is going in with the fv3_tiled_warmed_restart file.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA let's try and get this one merged next...

**Review by GeorgeGayno-NOAA — APPROVED** [review]
I compiled the branch on Hera and ran the unit tests with no issues.

**Pull request merged**
