### PR TITLE
Enable UFS_UTILS support on Gaea C6

### LINKED ISSUE #960: UFS_UTILS on C6
The spack-stack is available on the Gaea C6 and wondering if  UFS_UTILS is tested or if there is a plan to test it on the Gaea C6 platform.
/autofs/ncrc-svm1_proj/epic/spack-stack/spack-stack-1.6.0/envs/unified-env-c6/install/modulefiles/Core

### PR DESCRIPTION
**Pull request by BijuThomas-NOAA**
## DESCRIPTION OF CHANGES: 
This PR is for porting UFS_UTILS on the Gaea C6 platform. Using spack-stack-1.6.0 libraries, executables were successfully built on Gaea C6. The following files in the UFS_UTILS package were updated/created:

- modulefiles/build.gaeaC6.intel.lua
- sorc/machine-setup.sh

## TESTS CONDUCTED: 
The UFS_UTILS executables were tested successfully within the HAFS system.

Hash 441a468 was successfully compiled on all Tier 1 machines.

## DEPENDENCIES:
None.

## DOCUMENTATION:
N/A

## ISSUE: 
Fixes #960.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@BijuThomas-NOAA - you did not complete the PR documentation - "Description of Changes", "Tests Conducted", etc.

**Comment by GeorgeGayno-NOAA** [comment]
What about the `./fix/link_fixdirs.sh` file? Does that need to be updated?

**Comment by GeorgeGayno-NOAA** [comment]
Hash 914c3a1 was successfully compiled on all Tier 1 machines.

**Comment by BijuThomas-NOAA** [comment]
> What about the `./fix/link_fixdirs.sh` file? Does that need to be updated?

@GeorgeGayno-NOAA Regarding the HAFS system, no changes in link_fixdirs.sh are needed. HAFS was completed successfully on Gaea C6 with the UFS_UTILS executables.

**Comment by GeorgeGayno-NOAA** [comment]
@BijuThomas-NOAA - please merge the latest updates from 'develop' to your branch.

**Comment by BijuThomas-NOAA** [comment]
> @BijuThomas-NOAA - please merge the latest updates from 'develop' to your branch.

Done

**Comment by GeorgeGayno-NOAA** [comment]
> > @BijuThomas-NOAA - please merge the latest updates from 'develop' to your branch.
> 
> Done

After the merge (441a468), the branch was successfully compiled on all Tier 1 machines.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
