### PR TITLE
change to trigger CI

### PR DESCRIPTION
**Pull request by edwardhartnett**

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, for some reason MPI builds on MacOS stopped working. The same thing happened in NCEPLIBS-ncio, in which a build that worked just a few weeks ago on MacOS, stopped working. Grrr!!

I can't figure out what is going wring installing mpich on MacOS.

Meanwhile, @GeorgeGayno-NOAA if you merge this PR, and ignore MacOS failures, you can merge what you need to get your release out. The problems on MacOS have nothing to do with UFS_UTILS...

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA have you ever seen this error?

```
[  6%] Building Fortran object sorc/grid_tools.fd/shave.fd/CMakeFiles/shave.dir/shave_nc.F90.o
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], 0.0, u2, inbound, p1_1[0], p1_1[1], p1_1[2]);
            ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: note: did you mean 'isIntersect'?
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/mosaic_util.h:78:5: note: 'isIntersect' declared here
int isIntersect(struct Node node);
    ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1605:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], u1, u2, inbound, p1_0[0], p1_0[1], p1_0[2]);
            ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2118:8: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
    if(abs(dphi2 -dphi1) < M_PI) {
       ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2118:8: note: use function 'fabs' instead
    if(abs(dphi2 -dphi1) < M_PI) {
       ^~~
       fabs
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2[126](https://github.com/ufs-community/UFS_UTILS/actions/runs/3923039529/jobs/6706382283#step:19:127):39: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
      fint = f1 + (f2-f1)*(fac-dphi1)/abs(dphi);
                                      ^
/Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2126:39: note: use function 'fabs' instead
      fint = f1 + (f2-f1)*(fac-dphi1)/abs(dphi);
                                      ^~~
                                      fabs
```

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA have you ever seen this error?
> 
> ```
> [  6%] Building Fortran object sorc/grid_tools.fd/shave.fd/CMakeFiles/shave.dir/shave_nc.F90.o
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], 0.0, u2, inbound, p1_1[0], p1_1[1], p1_1[2]);
>             ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1602:6: note: did you mean 'isIntersect'?
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/mosaic_util.h:78:5: note: 'isIntersect' declared here
> int isIntersect(struct Node node);
>     ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:1605:6: error: implicit declaration of function 'insertIntersect' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>             insertIntersect(grid1List, intersect[0], intersect[1], intersect[2], u1, u2, inbound, p1_0[0], p1_0[1], p1_0[2]);
>             ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2118:8: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
>     if(abs(dphi2 -dphi1) < M_PI) {
>        ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2118:8: note: use function 'fabs' instead
>     if(abs(dphi2 -dphi1) < M_PI) {
>        ^~~
>        fabs
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2[126](https://github.com/ufs-community/UFS_UTILS/actions/runs/3923039529/jobs/6706382283#step:19:127):39: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
>       fint = f1 + (f2-f1)*(fac-dphi1)/abs(dphi);
>                                       ^
> /Users/runner/work/UFS_UTILS/UFS_UTILS/ufs_utils/sorc/fre-nctools.fd/shared_lib/create_xgrid.c:2126:39: note: use function 'fabs' instead
>       fint = f1 + (f2-f1)*(fac-dphi1)/abs(dphi);
>                                       ^~~
>                                       fabs
> ```

No, I have not. This is code we inherited from GFDL:
https://github.com/NOAA-GFDL/FRE-NCtools/tree/master/tools/libfrencutils

GFDL is usually responsive with questions.

**Comment by edwardhartnett** [comment]
OK, trying this in a different way in #749 . I will close this PR.

**Pull request closed without merging**
