### PR TITLE
global_cycle - Add soil moisture nudging for NoahMP option

### LINKED ISSUE #761: Update global_cycle for Noah-MP cycling
The `global_cycle` program only works with the Noah-LSM. The next upgrade of the GFS will use Noah-MP.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
When using NoahMP, output adjusted soil moisture to the restart files.

## TESTS CONDUCTED: 
Tested on a canned C96 case. See below for details.

The (Noah-based) regression tests were run on Hera and passed.

## DEPENDENCIES:
None.

## DOCUMENTATION:
N/A

## ISSUE: 
Fixes #761.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
Tested using a canned C96 test case on Hera: `/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/global_cycle_noahmp`

Attached is a plot of the total soil moisture differences between the input and output files (tile 1). The differences are of the magnitude expected for a 60-day relaxation to climatology.

Screenshot (36)

**Comment by GeorgeGayno-NOAA** [comment]
Same as the previous plot of total soil moisture, but for liquid soil moisture:

Screenshot (38)

Note the larger differences along the coastline. These are due to the input data file having non-zero moisture values at water points. The nudging is removing these spurious points.

Plot of land mask

Screenshot (40)

Plot of input liquid soil moisture. Note the non-zero moisture values over water.


Screenshot (42)

**Comment by GeorgeGayno-NOAA** [comment]
@HelinWei-NOAA can you review?

**Comment by HelinWei-NOAA** [comment]
@GeorgeGayno-NOAA Is the soil moisture increment due to the nudging calculated in sfcsub.f?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Is the soil moisture increment due to the nudging calculated in sfcsub.f?

Yes.

**Review by HelinWei-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
@HelinWei-NOAA are there any additional updates required for NoahMP? If not, I can close #761. 

Fractional grids will be worked under #549.

**Comment by HelinWei-NOAA** [comment]
> @HelinWei-NOAA are there any additional updates required for NoahMP? If not, I can close #761.
> 
No at this moment.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
