### PR TITLE
Starting to add doxygen, moved FindNetCDF.cmake and FindESMF.cmake into project, edit README

### LINKED ISSUE #190: Add .cmake files to repo, stop using submodule
See https://github.com/NOAA-EMC/NCEPLIBS/issues/128

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #171 
Fixes #190 
Part of #191

Dealing with submodule, starting to add docs.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
PR #187 is next in the queue.  

Should this PR go in before #188 or does it matter?

**Comment by edwardhartnett** [comment]
This can wait until #187 is merged...

**Comment by GeorgeGayno-NOAA** [comment]
#187 was merged.  We can do this PR next, then #188.  Orion is back up, so I can do a quick compile on all our officially supported machines.

**Comment by GeorgeGayno-NOAA** [comment]
> #187 was merged. We can do this PR next, then #188. Orion is back up, so I can do a quick compile on all our officially supported machines.

Ensure you merge the latest updates from develop to your branch.

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett  When I clone your branch, I see a zero byte .gitmodules file.  And I see an empty CMakeModules directory.  All package finds are now under ./cmake.  So can the first two items be removed?

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA good question! I will investigate and remove them if it works...

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA I think this is ready to merge.

**Comment by GeorgeGayno-NOAA** [comment]
I was able to remove empty directory CMakeModules with no impact.

**Comment by GeorgeGayno-NOAA** [comment]
The branch at 60f7d34 at successfully compiled on WCOSS-Dell, WCOSS-Cray, Hera and Orion.  It failed on Jet, because I am pointing to Dom's NCEPLIBS.  And he recently renamed and removed his directories.  So the failure is not due to changes under this PR.  Will merge.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
I don't know doxygen.  But I trust Ed's doxygen updates are correct.  The updates to the build system are working.

**Pull request merged**
