### PR TITLE
Add gblevents to UFS_UTILS

### LINKED ISSUE #523: Add fortran subprogram gblevents.f from w3emc to UFS_UTILS to solve circular dependency problem in NCEPLIBS?
@GeorgeGayno-NOAA we have a fortran subprogram in NCEPLIBS-w3emc which should probably be in UFS_UTILS.

According to @kgerheiser:

> It's that gblevents.f program which uses nemsio and sigio.
> 
> https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/gblevents.f
> 
> It seems to me that it should be moved out of w3emc. Into it's own repo? UFS_UTILS? I think it was put there just because that repo is the dumping ground for miscellaneous things. Then, w3emc would have no dependencies.

### PR DESCRIPTION
**Pull request by kgerheiser**
Per @edwardhartnett's direction I have added gblevents to UFS_UTILS.

UFS_UTILS is meant to be a temporary place for gblevents so that a circular dependency between nemsio and w3emc can be resolved.

Fix #523

### CODE REVIEW

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
Are we waiving the unit test requirement for this?

**Comment by GeorgeGayno-NOAA** [comment]
Your branch compiled just fine on Orion, Hera, Jet, WCOSS-Cray and WCOSS-Dell. The library built, and everything installed without warnings. However, I don't know enough about CMake to critique the three associated CMake files.

**Comment by GeorgeGayno-NOAA** [comment]
It does not appear the Doxygen is being built.

**Comment by kgerheiser** [comment]
> Are we waiving the unit test requirement for this?

Yes, I don't think @edwardhartnett would mind in this case. UFS_UTILS is just supposed to be a temporary home. The important thing is to get rid of the circular dependency.

> Your branch compiled just fine on Orion, Hera, Jet, WCOSS-Cray and WCOSS-Dell. The library built, and everything installed without warnings. However, I don't know enough about CMake to critique the three associated CMake files.

It is for when another project would use gblevents in CMake for `find_package(gblevents)`.

> It does not appear the Doxygen is being built.

Oh, good catch. I think I have to add a `docs` directory and maybe some Doxygen configuration.

**Comment by GeorgeGayno-NOAA** [comment]
> > Are we waiving the unit test requirement for this?
> 
> Yes, I don't think @edwardhartnett would mind in this case. UFS_UTILS is just supposed to be a temporary home. The important thing is to get rid of the circular dependency.
> 
> > Your branch compiled just fine on Orion, Hera, Jet, WCOSS-Cray and WCOSS-Dell. The library built, and everything installed without warnings. However, I don't know enough about CMake to critique the three associated CMake files.
> 
> It is for when another project would use gblevents in CMake for `find_package(gblevents)`.
> 
> > It does not appear the Doxygen is being built.
> 
> Oh, good catch. I think I have to add a `docs` directory and maybe some Doxygen configuration.

And maybe update the README file: https://github.com/NOAA-EMC/UFS_UTILS/blob/develop/README.md

**Comment by kgerheiser** [comment]
I have updated the documentation to the best of my ability.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser The doxygen table of contents was not listing gblevents. I updated ./docs/user_guide.md as follows and it worked:

```
diff --git a/docs/user_guide.md b/docs/user_guide.md
index f759d00c..0ce8530a 100644
--- a/docs/user_guide.md
+++ b/docs/user_guide.md
@@ -31,6 +31,10 @@ https://github.com/NOAA-EMC/UFS_UTILS.
   generated from the Great Lakes Operational Forecast System (GLOFS)
   in an FV3 surface restart file.

+- <a href="gblevents/index.html">gblevents</a> -
+  Prepares observational prepbufr reports for subsequent quality
+  control and analysis programs.
+
 - <a href="global_cycle/index.html">global_cycle</a> -
   Updates the GFS surface conditions using external snow and sea ice
   analyses. Updates monthly climatological fields such as plant
```

**Comment by GeorgeGayno-NOAA** [comment]
See here: https://www.emc.ncep.noaa.gov/jcsda/ggayno/doxygen/html/index.html

**Comment by kgerheiser** [comment]
Yes, I missed that that. Thanks. I have updated it.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Ready to merge.

**Comment by kgerheiser** [comment]
No, there is not. I mistakenly copied that over from the w3nco flags.

**Pull request merged**
