### PR TITLE
Port UFS_UTILS to WCOSS2

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Add the following for WCOSS2

- Build modules
- Consistency test driver scripts.
- Driver script for creating new grids.

## TESTS CONDUCTED: 
All testing is documented in #559.
- https://github.com/ufs-community/UFS_UTILS/issues/559#issuecomment-1177824601
- https://github.com/ufs-community/UFS_UTILS/issues/559#issuecomment-1177859786
- https://github.com/ufs-community/UFS_UTILS/issues/559#issuecomment-1177970126
- https://github.com/ufs-community/UFS_UTILS/issues/559#issuecomment-1177975915
- https://github.com/ufs-community/UFS_UTILS/issues/559#issuecomment-1178012197
- https://github.com/ufs-community/UFS_UTILS/issues/559#issuecomment-1178049857

## DEPENDENCIES:
None.

## DOCUMENTATION:
N/A

## ISSUE: 
#559

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
Note - the `cpld_gridgen` program does not work on WCOSS2. But we can hold up this merge any longer. It will be fixed under #663.

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA and @LarissaReames-NOAA - Sorry for the short suspense, but can you please review this. WCOSS2 is already online. I should have completed this a month ago. Thanks.

**Comment by JeffBeck-NOAA** [comment]
@GeorgeGayno-NOAA, this looks good to me.  Was the PR tested on other machines to make sure the build/regression tests still work there?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA, this looks good to me. Was the PR tested on other machines to make sure the build/regression tests still work there?

I only have access to Hera, Orion, Jet, WCOSS1 (soon to be retired) and WCOSS2. I am not even sure who the focal points are for the other machines. They are welcome to test my branch before I merge.

**Comment by GeorgeGayno-NOAA** [comment]
#667 should be also tested on other machines as I am removing stuff, which is more dangerous than adding stuff.

**Comment by JeffBeck-NOAA** [comment]
Thanks, @GeorgeGayno-NOAA.  I tested both the develop andyour own branch on Cheyenne, but ended up with this build error:

```
-- Configuring done
CMake Error at sorc/global_cycle.fd/CMakeLists.txt:27 (add_library):
  Cannot find source file:

    ../../ccpp-physics/physics/sfcsub.F

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at sorc/global_cycle.fd/CMakeLists.txt:27 (add_library):
  No SOURCES given to target: global_cycle_lib
```

I'm not sure why it's looking for a relative `../../ccpp-physics` directory within the stand-alone UFS_UTILS build.

This is not related to your PR, though, so I will go ahead and approve.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by JeffBeck-NOAA** [comment]
Thanks, @GeorgeGayno-NOAA. I built things successfully on Cheyenne, but can't run the regression tests there since rt.sh isn't set up yet for that platform.

**Comment by JeffBeck-NOAA** [comment]
Looks like there's more work involved for rt.sh on Cheyenne:

```
***ERROR*** unsupported machine
Syntax: link_fv3gfs.sh ( nco | emc ) ( cray | dell | hera | jet | orion | s4 )
rt.sh: line 97: ./driver.cheyenne.sh: No such file or directory
```

**Pull request merged**
