### PR TITLE
Update the chgres_cube.rst documentation

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
Update the chgres_cube.rst documentation file to match the version in 'develop' and the MRW App v1.1.

Issue #175.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA and @LarissaReames-NOAA - I will need your help to update this file for the new GRIB2 datasets.

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA  Don't forget about this PR before making additional updates to release/public-v2

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA  Can we knock out this PR next?

**Review by JeffBeck-NOAA — APPROVED** [review]
@GeorgeGayno-NOAA, This looks good to merge into the release branch for now.  Afterward, @LarissaReames-NOAA and I can open a separate PR to work on documentation of the regional GRIB2 functionality.  How does that sound?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA, This looks good to merge into the release branch for now. Afterward, @LarissaReames-NOAA and I can open a separate PR to work on documentation of the regional GRIB2 functionality. How does that sound?

That sounds good.

**Pull request merged**
