### PR TITLE
global_cycle - Fix definition of OROFIX in ./ush/global_cycle.sh

### LINKED ISSUE #890: Fix definition of OROFIX in global_cycle.sh
It should match the definition in global_cycle_driver.sh:

`OROFIX=${OROFIX:-$FIX_DIR/orog/${CASE}}`

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Fix the definition of OROFIX in `global_cycle.sh` to match that in `global_cycle_driver.sh`.

## TESTS CONDUCTED: 

- [x] Compile branch on Hera and run the global_cycle consistency tests. Done using affbcdc.
- [x] Run unit tests locally on Hera using affbcdc.

## DEPENDENCIES:
None.

## DOCUMENTATION:
N/A

## ISSUE: 
Fixes #890.

## CONTRIBUTORS : 
@CatherineThomas-NOAA

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@CatherineThomas-NOAA do you want to run a quick test before I merge?

**Comment by CatherineThomas-NOAA** [comment]
@GeorgeGayno-NOAA 
Thanks for prepping the PR.  Yes, I'll set up a test now.

**Comment by CatherineThomas-NOAA** [comment]
@GeorgeGayno-NOAA
The test ran successfully and looks good to me.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA The test ran successfully and looks good to me.

Great. Will merge.

**Pull request merged**
