### PR TITLE
Change "regression test" in our cron script to the more honest "consistency check."

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #434 

Change "regression test" in our cron script to the more honest "consistency check."

Let's not claim to be doing regression tests - we are doing nothing of the kind.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA would there be any consequence of changing the output from "regression.log" to "consistency.log"?

That is, are there any downstream scripts the depend on the name being "regression.log"?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA would there be any consequence of changing the output from "regression.log" to "consistency.log"?
> 
> That is, are there any downstream scripts the depend on the name being "regression.log"?

No.

**Review by kgerheiser — APPROVED** [review]

**Review by GeorgeGayno-NOAA — COMMENTED** [review]
Do you want to rename the directory from 'reg_tests' to something else?

**Comment by edwardhartnett** [comment]
We will keep the directory name because changing it will make it hard to maintain releases...

**Pull request merged**
