### PR TITLE
turn on WARN_AS_ERROR for global_cycle

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #191 
Part of #398 

Turn on WARN_AS_ERROR for global_cycle.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
The github build checks seem stuck.

**Comment by edwardhartnett** [comment]
Well GitHub is stuck. @kgerheiser , @aerorahul any ideas how to unstick it?

**Comment by aerorahul** [comment]
Not really.  Github's been weird today.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA can you approve this please, and we can get this turned on...

**Review by GeorgeGayno-NOAA — APPROVED** [review]
I approve.

**Pull request merged**
