### PR TITLE
Incorporate BNU soil type data

### LINKED ISSUE #705: Incorporate BNU soil type data
Incorporate the BNU soil type data to support the regional model.

Data is available here: https://www2.mmm.ucar.edu/wrf/users/download/get_sources_wps_geog.html#optional

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Updates to create model grids using the new Beijing Normal Univ. soil type data.

## TESTS CONDUCTED: 
See below for details.

## DEPENDENCIES:
None.

## DOCUMENTATION:
Updated for new dataset. See: https://georgegayno-noaaufs-utils.readthedocs.io/en/feature-bnu_soil/ufs_utils.html#id57

## ISSUE: 
Fixes #705

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
First, ensure these changes don't affect the current capability. The branch at 144c86b was compiled on Hera, Orion, Jet and WCOSS2 (Cactus). The `grid_gen` consistency tests were run. All tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
Next, create a grid(s) using the new BNU soil data. Using the branch at 144c86b, a regional ESG grid was created on Orion, Hera and Jet. On WCOSS2, regional ESG, global C96 and global C768 grids were created. All model grid soil type files were inspected visually and compared to the original data. All tests passed.

**Review by barlage — APPROVED** [review]
Changes look complete to me.

**Review by JeffBeck-NOAA — COMMENTED** [review]
@GeorgeGayno-NOAA, I see updates to the docs and driver scripts, but not to the code.  How does the code know what to do with "bnu.30s"?  Does it just search for whatever string is provided?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA, I see updates to the docs and driver scripts, but not to the code. How does the code know what to do with "bnu.30s"? Does it just search for whatever string is provided?

The path/name of the soil type file is a namelist entry for `sfc_climo_gen` (`input_soil_type_file` in `./ush/sfc_climo_gen.sh`). The program expects that this file has a 'soil_type' record, lat/lon records for geo-referencing, and a few attribute records. So as long as the soil type file contains these records, the program should work. For users that create grids using the scripts in `./driver_scripts`, the soil type file is selected using the `soil_type_src` variable. I know that some groups do not use those scripts to create grids. So, you are welcome to run your own tests.

**Comment by JeffBeck-NOAA** [comment]
> > @GeorgeGayno-NOAA, I see updates to the docs and driver scripts, but not to the code. How does the code know what to do with "bnu.30s"? Does it just search for whatever string is provided?
> 
> The path/name of the soil type file is a namelist entry for `sfc_climo_gen` (`input_soil_type_file` in `./ush/sfc_climo_gen.sh`). The program expects that this file has a 'soil_type' record, lat/lon records for geo-referencing, and a few attribute records. So as long as the soil type file contains these records, the program should work. For users that create grids using the scripts in `./driver_scripts`, the soil type file is selected using the `soil_type_src` variable. I know that some groups do not use those scripts to create grids. So, you are welcome to run your own tests.

Thanks for the explanation, @GeorgeGayno-NOAA.  I think this looks good!

**Review by JeffBeck-NOAA — APPROVED** [review]
Thanks for the explanation, @GeorgeGayno-NOAA. I think this looks good!

**Pull request merged**
