### PR TITLE
delete global_chgres

### LINKED ISSUE #298: remove global_chgres and associated scripts
As discussed in #167.

Remove global_chgres and scripts:
./ush/global_chgres.sh
./ush/global_chgres_driver.sh

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #298 
Part of #167 

Removed global_chgres.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
You know maybe we should not be doing this at all.

If we are still supporting this in public-v2, then we are just going to have to maintain it on that branch. We might as well have it on develop as well, for easy testing...

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA OK, if we're going to do this, I guess we should do this.

Once we delete global_chgres it will only be maintained on the public-v2 branch. It will receive no help with documentation and testing.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA shall we merge this? You must review it...

**Review by GeorgeGayno-NOAA — CHANGES_REQUESTED** [review]
global_chgres is the only ufs_utils program that uses the 'landsfcutil' and the 'nemsiogfs' libraries.  That what originally prompted this task - to get rid of nemsiogfs.  So you can eliminate the find_package calls for those libraries.  And remove their module load from all files in ./modulefiles.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA I've removed nemsiogfs and landsfcutil from the CMake and module files...

**Comment by GeorgeGayno-NOAA** [comment]
Let me do a quick compile on all our machines.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Successfully built with Intel on WCOSS-Cray, WCOSS-Dell, Jet and Orion.   Successfully built with Gnu and Intel on Hera.

**Pull request merged**
