### PR TITLE
doxygen for fvcom_tools.fd

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #338 
Part of #191 

More doxygen work.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
I've sent an email asking if there are any tests to go with this code.

**Review by GeorgeGayno-NOAA — COMMENTED** [review]
I am getting a doxygen warning for process_FVCOM.f90.  If I make this change, I get rid of it.

```
-!> @file
-!!
-!! This is the code to put lake surface temperature and aerial ice
+!> This is the code to put lake surface temperature and aerial ice
 !! concentration from GLERL-provided FVCOM forecast files (which have
 !! already been mapped to the FV3-LAM grid) into sfc_data.nc.
```
That file contains a driver program.  It is not a module with multiple routines.  So I guess in that case the @file is not needed?

**Comment by edwardhartnett** [comment]
Stand by, I will take a look...

**Comment by edwardhartnett** [comment]
OK, the file process_FVCOM.F90 was not originally part of this PR, but I've added it.

This PR does not fix all the warnings in the fvcom util yet, it's just the first few files in that directory. More will be coming in future PRs.

**Comment by GeorgeGayno-NOAA** [comment]
> OK, the file process_FVCOM.F90 was not originally part of this PR, but I've added it.
> 
> This PR does not fix all the warnings in the fvcom util yet, it's just the first few files in that directory. More will be coming in future PRs.

Great.  I will take a look.

**Comment by GeorgeGayno-NOAA** [comment]
I am still getting a warning: 

`sorc/fvcom_tools.fd/process_FVCOM.f90:11: warning: return type of member process_fvcom is not documented`

Do you want to fix it under this PR or a subsequent one?

**Comment by edwardhartnett** [comment]
I am still getting these warnings:

```
/home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:29: warning: Member drmissing (variable) of module kinds is not documented.
/home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:21: warning: Member i_byte (variable) of module kinds is not documented.
/home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:20: warning: Member i_short (variable) of module kinds is not documented.
/home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:28: warning: Member imissing (variable) of module kinds is not documented.
/home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:14: warning: Member len_sta_name (variable) of module kinds is not documented.
/home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:27: warning: Member rmissing (variable) of module kinds is not documented.
```

I will try and fill some of them in. @GeorgeGayno-NOAA extra scrutiny here because I'll be making some educated guesses...

**Comment by edwardhartnett** [comment]
OK, I filled in some more documentation. No warnings in this directory now, but it's still not complete. The module files are not fully documented yet. But we will hit that in a future PR.

**Comment by GeorgeGayno-NOAA** [comment]
> I am still getting these warnings:
> 
> ```
> /home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:29: warning: Member drmissing (variable) of module kinds is not documented.
> /home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:21: warning: Member i_byte (variable) of module kinds is not documented.
> /home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:20: warning: Member i_short (variable) of module kinds is not documented.
> /home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:28: warning: Member imissing (variable) of module kinds is not documented.
> /home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:14: warning: Member len_sta_name (variable) of module kinds is not documented.
> /home/ed/UFS_UTILS/sorc/fvcom_tools.fd/kinds.f90:27: warning: Member rmissing (variable) of module kinds is not documented.
> ```
> 
> I will try and fill some of them in. @GeorgeGayno-NOAA extra scrutiny here because I'll be making some educated guesses...

Your definitions are what I would have guessed.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Branch compiles with no doxygen warnings.  Go ahead and merge.

**Pull request merged**
