### PR TITLE
Rearrange allocation of hgt_1d in mtnlm7_oclsm.f to fix errors on macOS

### PR DESCRIPTION
**Pull request by kgerheiser**
I've been running various UFS_UTILS on my Desktop and I re-discovered #243 in develop.

The problem was fixed in `release/public-v2`, but it still exists in the develop branch.

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
How are we going to test this?

Firstly, seems like we would need a macos build of UFS_UTILS in GitHub...

**Comment by kgerheiser** [comment]
That reminds me, I do have a build for macOS. I was waiting for your caching PR to be merged first.

**Comment by GeorgeGayno-NOAA** [comment]
Looks fine to me.  Let me run the standard regression test (./reg_tests/grid_gen) on our supported machines.

**Comment by GeorgeGayno-NOAA** [comment]
I checked out Kyle's branch at 9aadb4d on Hera, Jet, Orion, WCOSS-Dell and WCOSS-Cray.  His branch was built successfully, and the "grid_gen" regression test passed.  Will merge.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Successfully tested on Hera, Orion, Jet and WCOSS.  Will merge.

**Pull request merged**
