### PR TITLE
Remove goto statements from chgres_cube

### PR DESCRIPTION
**Pull request by akubaryk**
## DESCRIPTION OF CHANGES: 
The WAM option of chgres_cube uses routines from NRLMSISE-00, which contain numerous 'goto' statements. Replace it with the more current MSIS 2.1 library (which has no 'goto' statements).

## TESTS CONDUCTED: 
Regression test run for WAM confirmed to function -- regression test baseline will need updating.

## DEPENDENCIES:
N/A

## DOCUMENTATION:
N/A

## ISSUE: 
Related to #759

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@akubaryk I will review. Be sure to merge the latest updates from 'develop' to your branch.

**Comment by GeorgeGayno-NOAA** [comment]
@akubaryk I was able to compile your branch. But when I tried to run our WAM-based regression test, it broke. May I update your branch with some fixes?

**Comment by GeorgeGayno-NOAA** [comment]
@akubaryk please merge in the latest updates from 'develop'. Then, I will do some final testing and merge.

**Comment by GeorgeGayno-NOAA** [comment]
@akubaryk The chgres_cube routines should have doxygen. I added it to wam_climo_data.f90 at eb12905. Please check. And replace the ??? with correct comments.  We don't need doxygen in the msis library.

**Comment by GeorgeGayno-NOAA** [comment]
@akubaryk I had to fix a bug with the unit test (35edbed). It would not compile on WCOSS2.

**Comment by akubaryk** [comment]
I have pulled in the latest updates and added some details to the doxygen in wam_climo_data.

**Comment by GeorgeGayno-NOAA** [comment]
Before merging, run some final tests using the @akubaryk branch at f8bec8a.

On Dogwood, the branch was compiled successfully, the unit tests ran successfully, and the doxygen was created without warnings. The `c96.fv3.netcdf2wam.sh` regression test failed as expected due to differences between the new NRLMSIS2.1 library and the old NRLMSISE-00 library. Here are the differences from the baseline:

```
CHECK out.atm.tile1.nc          + /lfs/h2/emc/global/noscrub/George.Gayno/util/nccmp/nccmp-1.8.5.0/src/nccmp -dmfqS out.atm.tile1.nc /lfs/h2/emc/nems/noscrub/emc.nems/UFS_UTILS/reg_tests/chgres_cube/baseline_data/c96_fv3_netcdf2wam/out.atm.tile1.nc
Variable Group   Count          Sum      AbsSum          Min       Max     Range         Mean     StdDev
zh       /      663539 -8.49367e+08 8.75024e+08     -3315.59   538.305    3853.9     -1280.06    1289.55
t        /      663551 -3.55417e+06 4.44218e+06     -30.7631   10.0412   40.8043     -5.35628    9.01491
spo      /      738534     -395.629     1852.24   -0.0137775  0.014633 0.0284105 -0.000535695 0.00405962
spo2     /     1382398      7412.28        7519 -7.54148e-05 0.0297442 0.0298196    0.0053619 0.00911125
```

```
CHECK out.atm.tile2.nc+ /lfs/h2/emc/global/noscrub/George.Gayno/util/nccmp/nccmp-1.8.5.0/src/nccmp -dmfqS out.atm.tile2.nc /lfs/h2/emc/nems/noscrub/emc.nems/UFS_UTILS/reg_tests/chgres_cube/baseline_data/c96_fv3_netcdf2wam/out.atm.tile2.nc
Variable Group   Count          Sum      AbsSum          Min       Max     Range         Mean     StdDev
zh       /      663536 -8.49367e+08 8.75024e+08     -3315.62   538.305   3853.93     -1280.06    1289.55
t        /      663550 -3.55417e+06 4.44218e+06     -30.7631   10.0412   40.8043     -5.35629    9.01491
spo      /      738534     -395.629     1852.24   -0.0137775  0.014633 0.0284105 -0.000535695 0.00405962
spo2     /     1382400      7412.28     7518.99 -7.53999e-05 0.0297442 0.0298196    0.0053619 0.00911124
```

```
CHECK out.atm.tile3.nc+ /lfs/h2/emc/global/noscrub/George.Gayno/util/nccmp/nccmp-1.8.5.0/src/nccmp -dmfqS out.atm.tile3.nc /lfs/h2/emc/nems/noscrub/emc.nems/UFS_UTILS/reg_tests/chgres_cube/baseline_data/c96_fv3_netcdf2wam/out.atm.tile3.nc
Variable Group   Count        Sum      AbsSum          Min        Max     Range        Mean     StdDev
zh       /      663537 2.1573e+07 2.49348e+08     -2021.16    640.953   2662.11     32.5122     493.91
t        /      663528    -292958  2.0573e+06     -21.8264    13.1463   34.9727   -0.441515     4.6316
spo      /      730818   -4824.29     5060.36   -0.0281621 0.00245656 0.0306187 -0.00660121 0.00826247
spo2     /     1382397    4419.19     4528.03 -7.54297e-05  0.0229874 0.0230628  0.00319676 0.00569511
```
```
CHECK out.atm.tile4.nc+ /lfs/h2/emc/global/noscrub/George.Gayno/util/nccmp/nccmp-1.8.5.0/src/nccmp -dmfqS out.atm.tile4.nc /lfs/h2/emc/nems/noscrub/emc.nems/UFS_UTILS/reg_tests/chgres_cube/baseline_data/c96_fv3_netcdf2wam/out.atm.tile4.nc
Variable Group   Count          Sum      AbsSum          Min       Max     Range         Mean     StdDev
zh       /      663536 -8.47257e+08 8.73199e+08     -3315.47    540.93    3856.4     -1276.88    1288.74
t        /      663552 -3.54576e+06 4.43764e+06      -30.763    10.078    40.841     -5.34361    9.00888
spo      /      738485     -408.134      1857.3   -0.0142339 0.0145697 0.0288036 -0.000552665 0.00406604
spo2     /     1382400       7403.1     7509.76 -7.54148e-05 0.0297441 0.0298196   0.00535525 0.00910279
```

```
CHECK out.atm.tile5.nc+ /lfs/h2/emc/global/noscrub/George.Gayno/util/nccmp/nccmp-1.8.5.0/src/nccmp -dmfqS out.atm.tile5.nc /lfs/h2/emc/nems/noscrub/emc.nems/UFS_UTILS/reg_tests/chgres_cube/baseline_data/c96_fv3_netcdf2wam/out.atm.tile5.nc
Variable Group   Count          Sum      AbsSum          Min       Max     Range         Mean     StdDev
zh       /      663535 -8.47257e+08 8.73199e+08     -3315.47    540.93    3856.4     -1276.88    1288.74
t        /      663552 -3.54576e+06 4.43764e+06      -30.763    10.078    40.841     -5.34361    9.00888
spo      /      738485     -408.134      1857.3   -0.0142339 0.0145697 0.0288036 -0.000552665 0.00406604
spo2     /     1382400      7403.08     7509.79 -7.54148e-05 0.0297441 0.0298196   0.00535524  0.0091028
```

```
CHECK out.atm.tile6.nc+ /lfs/h2/emc/global/noscrub/George.Gayno/util/nccmp/nccmp-1.8.5.0/src/nccmp -dmfqS out.atm.tile6.nc /lfs/h2/emc/nems/noscrub/emc.nems/UFS_UTILS/reg_tests/chgres_cube/baseline_data/c96_fv3_netcdf2wam/out.atm.tile6.nc
Variable Group   Count          Sum      AbsSum          Min       Max     Range        Mean     StdDev
zh       /      663548 -7.57984e+08 7.87663e+08        -3063   308.344   3371.34    -1142.32    1144.93
t        /      663552 -3.24153e+06 3.89588e+06     -26.0903   5.46359   31.5539    -4.88513    7.72334
spo      /      748988     -977.463      2382.9   -0.0127479 0.0152791  0.028027 -0.00130505  0.0049774
spo2     /     1382400      7159.98      7265.3 -7.53999e-05 0.0292095 0.0292849  0.00517938 0.00848134
```

These differences were checked by the developers and found to be correct. Output from the regression test was used to coldstart the forecast model without problems.

**Comment by GeorgeGayno-NOAA** [comment]
The branch at f8bec8a was then compiled on Jet, Hera and Orion. The unit tests ran successfully. The `c96.fv3.netcdf2wam.sh` regression test failed as expected. Differences from the baseline were nearly identical to those on Dogwood.

On Hera, the branch was also compiled using the GNU compiler.  The unit tests ran successfully. The regression test failed, but the differences from the baseline were nearly identical to those using Intel.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
@akubaryk I will update your branch with the latest changes from develop, then merge it. Thanks for all your work.

**Pull request merged**
