### PR TITLE
Remove dependency on module_nwp_base.f90

### PR DESCRIPTION
**Pull request by DavidWright-NOAA**
## DESCRIPTION OF CHANGES: 
Current fvcom_tools does not work with GNU compiler (as stated in issue #596 ). Code previously resulted in a seg fault with the fcst_nwp object in the process_FVCOM.f90 file when using GNU (but not Intel). Fix presented here removes the use of pointers in the code base (specifically pointers to NULL()) and removes the need for module_nwp_base.f90. The file module_nwp_base.f90 has been removed completely along with the use of it in the CMake file to compile. The unit test for fvcom_tools has also been uncommented in tests/CMakeFile.

## TESTS CONDUCTED: 
Code was tested with the unit test for both Intel and GNU compilers and both passed. Further testing was done with a cold start surface file (sfc_data.nc) from UFS-SRW and personal fvcom files and behavior was as expected for GNU compiler.

## DEPENDENCIES:
No dependencies.

## DOCUMENTATION:
No documentation should need to be updated (to my knowledge) since the functionality remains the same.

## ISSUE: 
Resolves issue #596 

## CONTRIBUTORS (optional): 
@GeorgeGayno-NOAA provided some initial debugging of the code.

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
@DavidWright-NOAA, thanks for tracking this down!  Did your cold-start tests result in identical sfc_data.nc files between Intel and GNU?

**Comment by DavidWright-NOAA** [comment]
@JeffBeck-NOAA I just did an ncdiff on both .nc files (GNU and Intel generated) and they were identical in their outputs.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA I just did an ncdiff on both .nc files (GNU and Intel generated) and they were identical in their outputs.

Thanks, @DavidWright-NOAA!

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
Thanks @DavidWright-NOAA. I will merge your changes.

**Pull request merged**
