### PR TITLE
Create workflow for UFS_UTILS

### PR DESCRIPTION
**Pull request by kgerheiser**
Automatically builds UFS_UTILS on every push and commit. No code changes.

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]

**Comment by edwardhartnett** [comment]
Awesome!

**Comment by edwardhartnett** [comment]
This Fixes #182

**Comment by kgerheiser** [comment]
Does what mean use the head of develop?

For UFS_UTILS, it will use whatever commit is currently being tested (PR, etc).

It uses the develop branch of NCEPLIBS to its prerequisites

**Comment by GeorgeGayno-NOAA** [comment]
> Does what mean use the head of develop?
> 
> For UFS_UTILS, it will use whatever commit is currently being tested (PR, etc).
> 
> It uses the develop branch of NCEPLIBS for its prerequisites

I am asking about NCEPLIBS.  Should we point to a specific commit of NCEPLIBS?  If NCEPLIBS advances and UFS_UTILS is not ready for the latest update, will this test fail?  And if the test fails, are PRs rejected?

**Comment by kgerheiser** [comment]
I switched it to v1.2.0 (the latest release)

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA excellent questions! Kyle and I were recently discussing this very issue. As you point out this test uses the develop branch everywhere. We must also test against public releases.

In future tests and code need to be changed in harmony so that UFS_UTILS can work with any of the supported versions of NCEPLIBS, plus the develop branch. Changes to UFS_UTILS must not break compatibility with any of the supported versions.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
The latest change to use v1.2.0 of NCEPLIBS ran successfully under Kyle's branch.  Will merge.

**Pull request merged**
