### PR TITLE
Port the GDAS_INIT utility to Jet

### LINKED ISSUE #544: Port GDAS INIT scripts to Jet
Port these scripts to Jet: https://github.com/NOAA-EMC/UFS_UTILS/tree/develop/util/gdas_init

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
Port the utility to support the global_workflow group.

Fixes #544

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA Please run your own tests on Jet.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Please run your own tests on Jet.

Running tests now, will report back, thanks!

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I have run two tests on Jet:

clone with your PR branch: /lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd

1) ran global-workflow free-forecast mode...the gfsinit job ran successfully and produced cold start ICs

/lfs4/HFIP/hfv3gfs/Kate.Friedman/ptmp/comrot/pruu563/logs/2021073100/gfsinit.log
/lfs4/HFIP/hfv3gfs/Kate.Friedman/ptmp/comrot/pruu563/logs/2021073106/gfsinit.log

2) ran gdas_init offline successfully

/lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/config
/lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/log.data.v16retro
/lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/log.enkf
/lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/log.gdas
/lfs4/HFIP/hfv3gfs/Kate.Friedman/ptmp/gdas.init/output

Looks good to me, thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I have run two tests on Jet:
> 
> clone with your PR branch: /lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd
> 
> 1. ran global-workflow free-forecast mode...the gfsinit job ran successfully and produced cold start ICs
> 
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/ptmp/comrot/pruu563/logs/2021073100/gfsinit.log
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/ptmp/comrot/pruu563/logs/2021073106/gfsinit.log
> 
> 1. ran gdas_init offline successfully
> 
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/config
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/log.data.v16retro
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/log.enkf
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/git/fork_feature-init_path/sorc/ufs_utils.fd/util/gdas_init/log.gdas
> /lfs4/HFIP/hfv3gfs/Kate.Friedman/ptmp/gdas.init/output
> 
> Looks good to me, thanks!

Great. Add your review to this PR and I will merge.

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good and were tested successfully on Jet.

**Comment by GeorgeGayno-NOAA** [comment]
> Changes look good and were tested successfully on Jet.

Thanks @KateFriedman-NOAA. I will create a release for you. Maybe not today. Can you wait until next Monday?

**Comment by KateFriedman-NOAA** [comment]
> I will create a release for you. Maybe not today. Can you wait until next Monday?

Monday is fine! Thanks @GeorgeGayno-NOAA !

**Pull request merged**
