### PR TITLE
Release v1.10.0

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## CHANGES
- Update VERSION file. 
- Update doxygen readme file.
- Point to production location of ESMF v8.4.1.

## TESTS CONDUCTED: 
See below.

## DEPENDENCIES:
Wail until ESMF 8.4.1 is available (in the production directory) on WCOSS2 before merging.

## DOCUMENTATION:
Doxygen was rerun and looked correct:
https://www.emc.ncep.noaa.gov/jcsda/ggayno/doxygen/html/index.html

## ISSUE: 
Part of #796.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA and @ZhanZhang-NOAA - this creates version 1.10.0, which will be the tag you provide to NCO. If you require subsequent updates, I will create another release (i,e., 1.10.1).

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA and @ZhanZhang-NOAA - per your latest instructions, we will not merge this until ESMF v8.4.1 is available on WCOSS2.

**Comment by GeorgeGayno-NOAA** [comment]
The branch at bfddd2d (points to the prod location of the esmf library on wcoss2) was compiled on Dogwood. The `chgres_cube`, `cpld_gridgen` and `grid_gen` consistency tests all passed.

**Comment by GeorgeGayno-NOAA** [comment]
> The branch at [bfddd2d](https://github.com/ufs-community/UFS_UTILS/commit/bfddd2dba82c79d5e12146d5e75877f31bf3f7d1) (points to the prod location of the esmf library on wcoss2) was compiled on Dogwood. The `chgres_cube`, `cpld_gridgen` and `grid_gen` consistency tests all passed.

The unit tests were also run locally on Dogwood and passed.

**Comment by GeorgeGayno-NOAA** [comment]
The doxygen looks correct for v1.10.0:

https://www.emc.ncep.noaa.gov/jcsda/ggayno/doxygen/html/index.html

**Comment by GeorgeGayno-NOAA** [comment]
The branch at f85b349 was compiled on Dogwood in 'Debug' mode. The `chgres_cube` consistency tests ran without crashing.

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA and @ZhanZhang-NOAA - anything else required for HAFS?

**Comment by BinLiu-NOAA** [comment]
Thanks, @GeorgeGayno-NOAA! I think that's it for HAFSv1. Much appreciated!

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good to me.

**Comment by GeorgeGayno-NOAA** [comment]
> Looks good to me.

Thanks, @BinLiu-NOAA. Can you wait until Monday for the tag?

**Comment by BinLiu-NOAA** [comment]
> > Looks good to me.
> 
> Thanks, @BinLiu-NOAA. Can you wait until Monday for the tag?

@GeorgeGayno-NOAA, should be fine. Thanks!

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA and @ZhanZhang-NOAA - your tag is ready.

**Pull request merged**
