### PR TITLE
Update documentation for new AWS fixed files host

### LINKED ISSUE #926: Update documentation for new AWS fixed files host
The global workflow group has hosted the latest fixed files to AWS. Update the documentation accordingly.

https://noaa-nws-global-pds.s3.amazonaws.com/index.html#fix/

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Update the 'readthedocs' `chgres_cube.rst` file as follows:

- Link to the global workflow group's AWS bucket for global model 'fixed' files ('grid', mosaic, 'oro' and surface).
- Update for new 'oro' and surface file naming convention, which uses the ocean resolution in the file name.
- Minor style edits.

## TESTS CONDUCTED: 
No source code changes.

## DEPENDENCIES:
None.

## DOCUMENTATION:
Rebuild the `readthedocs`: https://georgegayno-noaaufs-utils.readthedocs.io/en/update_rtd/

## ISSUE: 
Fixes #926.

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Updates look good! Approve.

**Comment by GeorgeGayno-NOAA** [comment]
For some reason, the NOMADS links I changed are no longer working. Maybe being in the building makes a difference? At home, I can't access the nomads.weather.gov links with or without going through VPN. 

Revert to the original URLs at 6e287b9, which are working for me.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA can you verify some of the NOMADS links:
https://georgegayno-noaaufs-utils.readthedocs.io/en/update_rtd/ufs_utils.html#where-to-find-gfs-grib2-and-netcdf-data-for-global-applications

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA can you verify some of the NOMADS links: https://georgegayno-noaaufs-utils.readthedocs.io/en/update_rtd/ufs_utils.html#where-to-find-gfs-grib2-and-netcdf-data-for-global-applications

@GeorgeGayno-NOAA Yep, those NOMADS pages are what is listed on this page for the https access: https://www.nco.ncep.noaa.gov/pmb/products/gfs/

There is also a ftp version shown on that page but the ftp link isn't opening a page for me right now. Best to stick with the https page that you are using for your NOMADS links.

**Pull request merged**
