### PR TITLE
adding developer workflow

### LINKED ISSUE #731: Debug build should not turn on address santizer
The debug build of UFS_UTILS turns on address santizer for GNU. None of the other NCEPLIBS do. Address sanitizer is a does not play well with the debugger, so it does not work well as an option for the Debug build type.

I will remove it, and anyone who wants the address sanitizer can set CMAKE_Fortran_FLAGS to include it.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #719 
Fixes #731 

In this PR I add a developer workflow, which does the test code coverage report.

Also cause all the other workflows to only build once for each PR or commit to PR branch.

I also take address sanitizer out of the Debug build type on GNU compilers. It's best turned on in FLAGS.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, I think this is ready to merge and will help.

The test code coverage report is working in the "developer" workflow.

**Comment by GeorgeGayno-NOAA** [comment]
Approved. Be sure to merge the latest updates from develop.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett After I merged these changes to a branch in my fork, the workflows won't run. Something about a syntax error:

https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3688550261
https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3688550195

Do you know what is happening?

**Comment by edwardhartnett** [comment]
Yes I have fixes for both on my current PR #739

**Pull request merged**
