### PR TITLE
Release version 1.9

### LINKED ISSUE #753: Release Version 1.9.0
The HAFS group has requested a release to support the upcoming HAFS v1.0.0 implementation.

- Update the VERSION file.
- Use the tag name ufs_utils_1_9_0.
- After updating the VERSION file, rebuild the Doxygen documentation and update the gh-pages branch.
- Update the bullet list of items in the release notes, with links to the issues closed.
- After doing the release, create draft release notes (via cut and paste) for the next release, and update the spack repo.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Release version 1.9 in support of the HAFS v1.0 implementation.

## TESTS CONDUCTED: 
Some github actions tests are failing. But this is not due to problems with
ufs_utils code.

## DEPENDENCIES:
None.

## DOCUMENTATION:
The 'doxygen' and 'readthedocs' was generated. See below for details.

## ISSUE: 
Fixes #753.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
The 'readthedocs' was tested on the branch. See:
https://georgegayno-noaaufs-utils.readthedocs.io/en/feature-v1.9/ufs_utils.html

**Comment by GeorgeGayno-NOAA** [comment]
The 'doxygen' was generated and hosted in my space on rzdm:
https://www.emc.ncep.noaa.gov/jcsda/ggayno/doxygen/html/index.html

It includes a (currently empty) link to the v1.9.0 documentation.

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett Can the broken tests be fixed quickly, or can I merge anyway? It is not a problem with the ufs_utils code.

**Comment by edwardhartnett** [comment]
I can't figure it out, but we can turn off that required build and debug it after your release...

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good to me.

**Pull request merged**
