### PR TITLE
Bug fixes for Jet

### LINKED ISSUE #977: Spack-stack moved from /lfs4 to /contrib on Jet
Spack stack moved from the storage /lfs4 to a new storage space /contrib, following the failure of /lfs4.

The requires the update of module files for all softwares supported on Jet

Refs NOAA-EMC/global-workflow#2377

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Minor updates for Jet.

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [x] Compile branch on Jet using Intel. Done using 36a905f.
- [x] Run relevant consistency tests locally on Jet. Because of very slow turn-around times on Jet, a subset of each regression test was run using the 'debug' queue. All tests passed. Used 36a905f.

Describe any additional tests performed (using 36a905f)

The `gdas_init` utility was run for a 2021/03/07/00 test case to ensure that the `set_fixed_files.sh` script pointed to the correct input orography directory. The test passed.

## DEPENDENCIES:
None.

## DOCUMENTATION:
N/A

## ISSUE: 
Fixes #977.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA - thanks for your help.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @GeorgeGayno-NOAA !

**Comment by KateFriedman-NOAA** [comment]
FYI @InnocentSouopgui-NOAA , you'll want the updated hash for Jet after this goes in.

**Comment by InnocentSouopgui-NOAA** [comment]
Sure I will do that.

**Pull request merged**
