### PR TITLE
Gnu 10 flags

### LINKED ISSUE #206: UFS_UTILS will not build with gnu v10+ compilers
This is due to stricter requirements on argument types between subroutines per the Fortran 2008 standards (https://www.scivision.co/gfortran-type-mismatch-error/).

### PR DESCRIPTION
**Pull request by mkavulich**
GNU 10.0 and later compilers enforce stricter requirements on argument types between subroutines, which results in problems building some of the utilities. The quick and dirty fix is to add the flag `-fallow-argument-mismatch` to the fortran compiler call.

Just a note: according to the GNU project documentation on `-fallow-argument-mismatch`, "Using this option is *strongly* discouraged." So this code should be updated in the future to conform to the standard rather than ignoring the error.

Tests run: Built on MacOSX High Sierra (Version 10.13.6) with GNU 10.2.0 compilers, which previously failed. Also ran build and run tests as part of SRW app (release branch) workflow on Hera; all tests passed with no change in results (.nc input files created for model were bit-for-bit identical), though this is a trivial result since that was with intel compilers. None of the NOAA platforms support GNU 10 so this was mainly a sanity check.

Resolves #206

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Can you enter an issue describing this change and link to that issue in the PR?

All PRs should have an issue that describes the changes, and should be linked to that PR...

**Comment by mkavulich** [comment]
@edwardhartnett Done.

**Comment by GeorgeGayno-NOAA** [comment]
@mkavulich I don't think your branch is up-to-date with 'develop'.  Do a merge.  

Also, how much work would it be to fix the argument mismatches?

**Comment by mkavulich** [comment]
@GeorgeGayno-NOAA I am merging to the release branch, not develop, since that is where I have been testing. Since these branches are starting to diverge, maybe it is best to handle that in a separate PR?

I am not personally familiar enough with the code to know how much work it will take to fix the mismatched arguments, but I can tell you the locations where GNU spits out the errors (now reduced to warnings with the `-fallow-argument-mismatch` flag):

```
UFS_UTILS/sorc/global_chgres.fd/sfcsub.F:8389:22:

 8387 |         call w3movdat(fha4,ida,jda)
      |                      2
 8388 |       else
 8389 |         call w3movdat(fha,ida,jda)
      |                      1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/REAL(4)).

--------------------------------------------------------------------------------------------------------

UFS_UTILS/sorc/global_chgres.fd/sfcsub.F:8480:34:

 8476 |      &             kpds,kgds,lbms,data8,jret)
      |                                  2
......
 8480 |      &             kpds,kgds,lbms,data4,jret)
      |                                  1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).

--------------------------------------------------------------------------------------------------------

UFS_UTILS/sorc/global_cycle.fd/sfcsub.F:8389:22:

 8387 |         call w3movdat(fha4,ida,jda)
      |                      2
 8388 |       else
 8389 |         call w3movdat(fha,ida,jda)
      |                      1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/REAL(4)).

--------------------------------------------------------------------------------------------------------

UFS_UTILS/sorc/global_cycle.fd/sfcsub.F:8480:34:

 8476 |      &             kpds,kgds,lbms,data8,jret)
      |                                  2
......
 8480 |      &             kpds,kgds,lbms,data4,jret)
      |                                  1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).

--------------------------------------------------------------------------------------------------------

UFS_UTILS/sorc/chgres_cube.fd/model_grid.F90:1054:22:

  845 |   call MPI_BCAST(temp_num,10,MPI_CHAR,0,MPI_COMM_WORLD,error)
      |                 2     
......
 1054 |        call MPI_BCAST(dx,1,MPI_REAL8,0,MPI_COMM_WORLD,error)
      |                      1
Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/CHARACTER(*)).

```

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I am merging to the release branch, not develop, since that is where I have been testing. Since these branches are starting to diverge, maybe it is best to handle that in a separate PR?
> 
> I am not personally familiar enough with the code to know how much work it will take to fix the mismatched arguments, but I can tell you the locations where GNU spits out the errors (now reduced to warnings with the `-fallow-argument-mismatch` flag):
> 
> ```
> UFS_UTILS/sorc/global_chgres.fd/sfcsub.F:8389:22:
> 
>  8387 |         call w3movdat(fha4,ida,jda)
>       |                      2
>  8388 |       else
>  8389 |         call w3movdat(fha,ida,jda)
>       |                      1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/REAL(4)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/global_chgres.fd/sfcsub.F:8480:34:
> 
>  8476 |      &             kpds,kgds,lbms,data8,jret)
>       |                                  2
> ......
>  8480 |      &             kpds,kgds,lbms,data4,jret)
>       |                                  1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/global_cycle.fd/sfcsub.F:8389:22:
> 
>  8387 |         call w3movdat(fha4,ida,jda)
>       |                      2
>  8388 |       else
>  8389 |         call w3movdat(fha,ida,jda)
>       |                      1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/REAL(4)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/global_cycle.fd/sfcsub.F:8480:34:
> 
>  8476 |      &             kpds,kgds,lbms,data8,jret)
>       |                                  2
> ......
>  8480 |      &             kpds,kgds,lbms,data4,jret)
>       |                                  1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/chgres_cube.fd/model_grid.F90:1054:22:
> 
>   845 |   call MPI_BCAST(temp_num,10,MPI_CHAR,0,MPI_COMM_WORLD,error)
>       |                 2     
> ......
>  1054 |        call MPI_BCAST(dx,1,MPI_REAL8,0,MPI_COMM_WORLD,error)
>       |                      1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/CHARACTER(*)).
> ```

Sorry.  I see that now,  You are merging to the release branch.

**Comment by GeorgeGayno-NOAA** [comment]
'global_cycle' and 'global_chgres' are not used by the SRW App to my knowledge.  You might want to comment out their compilation.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I am merging to the release branch, not develop, since that is where I have been testing. Since these branches are starting to diverge, maybe it is best to handle that in a separate PR?
> 
> I am not personally familiar enough with the code to know how much work it will take to fix the mismatched arguments, but I can tell you the locations where GNU spits out the errors (now reduced to warnings with the `-fallow-argument-mismatch` flag):
> 
> ```
> UFS_UTILS/sorc/global_chgres.fd/sfcsub.F:8389:22:
> 
>  8387 |         call w3movdat(fha4,ida,jda)
>       |                      2
>  8388 |       else
>  8389 |         call w3movdat(fha,ida,jda)
>       |                      1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/REAL(4)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/global_chgres.fd/sfcsub.F:8480:34:
> 
>  8476 |      &             kpds,kgds,lbms,data8,jret)
>       |                                  2
> ......
>  8480 |      &             kpds,kgds,lbms,data4,jret)
>       |                                  1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/global_cycle.fd/sfcsub.F:8389:22:
> 
>  8387 |         call w3movdat(fha4,ida,jda)
>       |                      2
>  8388 |       else
>  8389 |         call w3movdat(fha,ida,jda)
>       |                      1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/REAL(4)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/global_cycle.fd/sfcsub.F:8480:34:
> 
>  8476 |      &             kpds,kgds,lbms,data8,jret)
>       |                                  2
> ......
>  8480 |      &             kpds,kgds,lbms,data4,jret)
>       |                                  1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
> 
> --------------------------------------------------------------------------------------------------------
> 
> UFS_UTILS/sorc/chgres_cube.fd/model_grid.F90:1054:22:
> 
>   845 |   call MPI_BCAST(temp_num,10,MPI_CHAR,0,MPI_COMM_WORLD,error)
>       |                 2     
> ......
>  1054 |        call MPI_BCAST(dx,1,MPI_REAL8,0,MPI_COMM_WORLD,error)
>       |                      1
> Warning: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/CHARACTER(*)).
> ```

I am not sure I understand the chgres_cube warning.  You can pass MPI_BCAST different data types.  So I am not sure how to fix this.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
The sfcsub.F warnings are not really mismatches as 'global_chgres' and 'global_cycle' are always run with 8-byte floats.  And the 'if' logic will ensure the correct call to getgb will occur.  I am not sure why there are warnings for chgres_cube.  MPI_BCAST can be called with different data types.  So I am not sure how to fix it.

**Pull request merged**
