### PR TITLE
GDAS_INIT utility - point to correct v16 retro GFS HPSS directory

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
The location of NCO's GFS v16 real-time parallel was moved on HPSS. Update the GDAS_INIT utility
accordingly. 

#558

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Thanks for alerting me to this and making the adjustment in gdas_init. Looks good!

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Will you be cutting a new tag after this change? Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Will you be cutting a new tag after this change? Thanks!

I could. Do want to wait until #544 is done?

**Comment by KateFriedman-NOAA** [comment]
> > @GeorgeGayno-NOAA Will you be cutting a new tag after this change? Thanks!
> 
> I could. Do want to wait until #544 is done?

Sure, what's your estimate on when 544 will be done? I'm happy to wait a bit. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> > > @GeorgeGayno-NOAA Will you be cutting a new tag after this change? Thanks!
> > 
> > 
> > I could. Do want to wait until #544 is done?
> 
> Sure, what's your estimate on when 544 will be done? I'm happy to wait a bit. Thanks!

I can't access HPSS from Jet yet (waiting for sys admin to help). So I am pulling data on Hera, then pushing it to Jet. So I am able to test the chgres part on Jet. Give me the rest of this week. If I can't get it done by then, I will create a release for you without #544.

**Comment by KateFriedman-NOAA** [comment]
> Give me the rest of this week. If I can't get it done by then, I will create a release for you without #544.

Okie dokie, works for me! Let me know if I can help test anything on Jet, I have HPSS access there.

**Pull request merged**
