### PR TITLE
More doxygen work

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #191 

More work on the doxygen documentation.

### CODE REVIEW

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Looks ok.

**Comment by edwardhartnett** [comment]
Are you looking at the output as well? You should do so, it is here: https://noaa-emc.github.io/UFS_UTILS/.

**Comment by GeorgeGayno-NOAA** [comment]
> Are you looking at the output as well? You should do so, it is here: https://noaa-emc.github.io/UFS_UTILS/.

I see that more of the files are now 'clickable'.  And the info in most of them looks ok.   However, I tend to recycle module names.  You will see multiple instances of  'driver.f90' and 'program_setup'.  When I click on https://noaa-emc.github.io/UFS_UTILS/sfc__climo__gen_8fd_2program__setup_8f90.html  Then click on the module program setup link (https://noaa-emc.github.io/UFS_UTILS/namespaceprogram__setup.html), it is pointing to the program-setup under chgres_cube, not sfc_climo_gen.  So I think it is getting confused by the duplicate files names.  I hope we don't have to rename all the modules with unique names.

**Comment by edwardhartnett** [comment]
We will not have to rename modules. Yes, there is some confusion about this in the output, but I'm sure we can straighten that out. I will do some browsing of on-line resources and see if I can figure it out.

But the files list is actually not the way most readers will interact with the docs. We will add a mainpage  that will be more user-friendly face on the docs.

I will merge this PR and add something to the mainpage for the next round, so you can see what I mean...

**Pull request merged**
