### PR TITLE
Feature/regional regtests

### PR DESCRIPTION
**Pull request by LarissaReames**
Added in new consistency tests that test a much broader swath of the capabilities of the grib2 read routine. I also converted the tests to be run in parallel instead of in sequence. 

Note that running these tests this will require @GeorgeGayno-NOAA to copy in the baseline and fix files for each test. On Hera those are here: `/scratch1/BMC/gsd-fv3/Larissa.Reames/chgres_cube/reg_tests/`
On Jet they are here: `/lfs4/NAGAPE/hpc-wof1/lreames/chgres_cube/reg_tests/`

There is at least one PR currently waiting to be merged that will require regeneration of one set of baseline tests (3km.conus.hrrr.newsfc.grib2)

Addresses Issue #181

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA The new tests failed for me on Hera because it could not find the 'nccmp' utility.  Variable NCCMP is not defined. In other scripts, I have to do:

`NCCMP=${NCCMP:-$(which nccmp)}`

**Comment by LarissaReames-NOAA** [comment]
> @LarissaReames-NOAA The new tests failed for me on Hera because it could not find the 'nccmp' utility. Variable NCCMP is not defined. In other scripts, I have to do:
> 
> `NCCMP=${NCCMP:-$(which nccmp)}`

Is this for the gnu compiler? I have no problems with the default intel compiler setting on Hera since nccmp is loaded in the corresponding modulefile. I double checked and I don't have any extra modules loading manually for that build.

**Comment by GeorgeGayno-NOAA** [comment]
> > @LarissaReames-NOAA The new tests failed for me on Hera because it could not find the 'nccmp' utility. Variable NCCMP is not defined. In other scripts, I have to do:
> > `NCCMP=${NCCMP:-$(which nccmp)}`
> 
> Is this for the gnu compiler? I have no problems with the default intel compiler setting on Hera since nccmp is loaded in the corresponding modulefile. I double checked and I don't have any extra modules loading manually for that build.
> 
> Edit: Scratch that, my bad. You're right, I'll put that in the driver script.

It is working for me on Jet now. Thanks. I am testing on WCOSS-Dell right now.

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA I moved the baseline files to WCOSS-Dell and created a driver script. However, one of the tests - `3-km CONUS HRRR W/ GSD PHYSICS AND SFC FROM FILE GRIB2 TEST` - is failing. The differences are not 'floating point' differences. And if I change the number of MPI tasks, it will suddenly pass. The differences are only with the 'w' field. All other records are identical. Some specifics:

On Jet with 18 tasks, it passed. But with 12 tasks, it fails:

```
+ nccmp -dmfqS out.atm.tile7.nc /lfs4/HFIP/emcda/George.Gayno/reg_tests/chgres_cube/baseline_data/3km_conus_hrrr_newsfc_grib2/out.atm.tile7.nc
Variable Group   Count      Sum  AbsSum        Min      Max    Range        Mean     StdDev
w        /     3332416 -4378.16 19296.4 -0.0283263 0.222837 0.251163 -0.00131381 0.00838594
```

On Dell with 12 tasks, it passes. But with 18 tasks, it fails:

```
+ nccmp -dmfqS out.atm.tile7.nc /gpfs/dell2/emc/modeling/noscrub/George.Gayno/ufs_utils.git/reg_tests/chgres_cube/baseline_data/3km_conus_hrrr_newsfc_grib2/out.atm.tile7.nc
Variable Group   Count     Sum  AbsSum       Min       Max    Range       Mean     StdDev
w        /     3332416 4378.16 19296.4 -0.222837 0.0283263 0.251163 0.00131381 0.00838594
```

And note how the differences (like standard deviation) are similar. Odd. If I difference the netcdf files, the 'w' differences are tied to the high terrain, especially in the western CONUS.

What could be going on?

**Comment by LarissaReames-NOAA** [comment]
@GeorgeGayno-NOAA Yeah, I've encountered issues like this before, specifically with w. I think in the past I've alleviated it by providing more memory (i.e. more nodes). I never figured out exactly what caused it, but I assumed it was some sort of memory issue with ESMF.

**Comment by GeorgeGayno-NOAA** [comment]
I updated the WCOSS-Dell script. It is on Hera: /scratch2/NCEPDEV/stmp1/George.Gayno/for.larissa

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA The WCOSS Dell driver has been added to the PR.

I have Cray and Orion versions as well.

**Comment by LarissaReames-NOAA** [comment]
> > @GeorgeGayno-NOAA The WCOSS Dell driver has been added to the PR.
> 
> I have Cray and Orion versions as well.

Where are they located? I don't see them in that folder on Hera.

**Comment by GeorgeGayno-NOAA** [comment]
> > > @GeorgeGayno-NOAA The WCOSS Dell driver has been added to the PR.
> > 
> > 
> > I have Cray and Orion versions as well.
> 
> Where are they located? I don't see them in that folder on Hera.

I just added them on Hera: /scratch2/NCEPDEV/stmp1/George.Gayno/for.larissa

**Comment by LarissaReames-NOAA** [comment]
> > > > @GeorgeGayno-NOAA The WCOSS Dell driver has been added to the PR.
> > > 
> > > 
> > > I have Cray and Orion versions as well.
> > 
> > 
> > Where are they located? I don't see them in that folder on Hera.
> 
> I just added them on Hera: /scratch2/NCEPDEV/stmp1/George.Gayno/for.larissa

Okay, they've been added.

**Comment by GeorgeGayno-NOAA** [comment]
> > > > > @GeorgeGayno-NOAA The WCOSS Dell driver has been added to the PR.
> > > > 
> > > > 
> > > > I have Cray and Orion versions as well.
> > > 
> > > 
> > > Where are they located? I don't see them in that folder on Hera.
> > 
> > 
> > I just added them on Hera: /scratch2/NCEPDEV/stmp1/George.Gayno/for.larissa
> 
> Okay, they've been added.

Ok. Please update your branch, then I can merge.

**Comment by LarissaReames-NOAA** [comment]
Branch is now up to date with develop.

**Comment by GeorgeGayno-NOAA** [comment]
The input and baseline data for the new tests has been installed on WCOSS-Dell, WCOSS-Cray, Hera, Jet and Orion. The branch was compiled on those machines. Then, the chgres_cube consistency test driver script was started. All tests ran and passed.

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA Any further changes or can this be merged?

**Comment by LarissaReames-NOAA** [comment]
> @LarissaReames-NOAA Any further changes or can this be merged?

I had @JeffBeck-NOAA give it a spin just to check that everything was working and he found an inaccuracy in the inline documentation about properly setting up environment variables to properly run when you don't have a NCEPDEV scratch directory. I've updated those instructions in all of the drivers, so it should be ready to go now.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Review by GeorgeGayno-NOAA — APPROVED** [review]
I approve.

But at some point I would investigate why that one test fails when number of tasks changes. It is always the 'w' field, and the differences from the baseline are consistent across machines.

**Pull request merged**
