### PR TITLE
Add TEST_FILE_DIR option to CMake build, where test data files can be found instead of using FTP. Use this in all CI runs to cache data.

### LINKED ISSUE #728: Add CMake option to allow data files to be found in local directory, allowing developer to keep local copy, and CI system to cache
We download a bunch of test data from the FTP site.

On the g2/g2c/grib_util projects I have added an option to CMakeLists.txt that allows a local directory to be checked for data before ftp is called. If the file is found in the local directory, then it is copied, otherwise it is fetched from FTP. This allows me to keep a local copy of the test data files. When I work on the code, cmake does not keep downloading the test files.

Also, and even better, the CI system can then cache the data files and not have to fetch them for each test run. This speeds up the CI a lot.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #719.
Fixes #728

In this PR I add handling for the TEST_FILE_DIR option in Cmake.

This allows the programmer to specify a local directory to check first, before downloading test data files from the FTP site.

I use this capability, and a cache, to cache the data for all CI runs as well. This prevents the CI system from downloading these test files hundreds of times per day.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
OK, this is ready to merge.

After this PR all CI workflows will used a cached version of the test data. This speeds up test runs.

**Comment by GeorgeGayno-NOAA** [comment]
I just tried the branch on Dogwood. I built the repo and ran the tests from scratch. Then, I removed two data files from the build directory. When I invoked CMake again, only the missing files were downloaded from the FTP site. So, your logic is working as intended.

```
-- Found sigio: /apps/ops/para/libs/intel/19.1.3.304/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
-- Set BUILD_TESTING to YES and build unit testing package under tests
-- TEST_FILE_DIR . THE_FILE gfs.v16.sfc.history.nc
-- TEST_FILE_DIR . THE_FILE gfs.v16.sfc2.history.nc
-- TEST_FILE_DIR . THE_FILE gfs.v16.atm.history.nc
-- TEST_FILE_DIR . THE_FILE gfs.v14.sfc.history.nemsio
-- Downloading file /lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/build/tests/chgres_cube/data/gfs.v14.sfc.history.nemsio.
-- TEST_FILE_DIR . THE_FILE gfs.v15.sfc.history.nemsio
-- Downloading file /lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS.upstream/build/tests/chgres_cube/data/gfs.v15.sfc.history.nemsio.
-- TEST_FILE_DIR . THE_FILE gfs.t00z.pgrb2.0p50.f000
-- TEST_FILE_DIR . THE_FILE C450_mosaic.nc
-- TEST_FILE_DIR . THE_FILE C450_grid.tile7.nc
-- TEST_FILE_DIR . THE_FILE C450_oro_data.tile7.nc
-- TEST_FILE_DIR . THE_FILE vegetation_type.viirs.igbp.0.1.nc
-- TEST_FILE_DIR . THE_FILE ocean_hgrid.nc
-- Configuring done
-- Generating done
```

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA yes, and if you want to keep a local copy of the data files on your machine(s) it can save some time.

But mostly the benefit here is that the CI system doesn't need to download all files for each CI run, possibly hundreds of times in a day. ;-)

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA if we can get this one approved and merged I we can continue with the CI work...

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
