### PR TITLE
Upgrade to spack-stack 1.8.0

### LINKED ISSUE #983: Update to spack-stack v1.9.2
It will be installed on all RDHPCS machines. The plan is to have the 'classic' and LLVM-compiled versions side-by-side. The global workflow will start with the 'classic' version.

The location of the stack on each machine is [here](https://gist.github.com/DavidHuber-NOAA/a75daea63a81959dba456424c644740e).

Note: the move to spack-stack v1.9.2 on Ursa was made during the port to that machine. See #1064. So, this issue will update Orion and Hercules.

Related to #879.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
## DESCRIPTION OF CHANGES: 
This upgrades UFS_Utils to spack-stack 1.8.0.  This upgrades a few libraries/packages:
cmake 3.23.1 -> 3.27.9
g2 3.4.5 -> 3.5.1
ip 4.3.3 -> 5.0.0
esmf 8.6.0 -> 8.6.1
nco 5.0.6 -> 5.1.6
wgrib2 2.0.8 -> 3.1.1

Also, as of ip/5.0.0, the sp library functions have been pulled into ip, so sp has been removed.  Lastly, the z library has been replaced by zlib-ng.  For more details, see the spack-stack v1.8.0 release notes (link to be provided when the release if finalized).

Official installations are not yet in place, so this will remain a draft until all platforms have been migrated for both Intel and GNU compilers.  As is, all unit and regression tests pass on Hera when compiled with Intel classic compilers.

Resolves #983 

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [ ] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
- [ ] Compile branch on Hera using GNU.
- [ ] Compile branch in 'Debug' mode on WCOSS2.
- [ ] Run unit tests locally on any Tier 1 machine.
- [ ] Run relevant consistency tests locally on all Tier 1 machines.

Optional test.

- [ ] Run full set of chgres_cube consistency tests on Hera.

## ISSUE: 
If this PR is resolving or referencing one or more issues, in this repository or elsewhere, list them here. For example, "Fixes issue mentioned in #123" or "Related to bug in https://github.com/NOAA-EMC/other_repository/pull/63"

## CONTRIBUTORS (optional): 
If others have contributed to this work aside from the PR author, list them here

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
The Intel and GCC builds failed due to not being able to find ipolates.  I'm not sure if this will require a new build cache, but will look into it in more detail as the work continues.

**Comment by DavidHuber-NOAA** [comment]
I've been informed by the spack-stack developers that we should wait for version 1.9.0, which will be more stable.  Closing.

**Comment by LarissaReames** [comment]
@DavidHuber-NOAA The RRFS team (cc @natalie-perlin ) need g2v3.4.9+ for a key feature in chgres_cube and that is not available in the present stack, so we'd like to consider upgrading to 1.8.0 at least on Hera. I know you closed this, but it looks like UWM upgraded to 1.8.0 today (PR ufs-community/ufs-weather-model/pull/2453 ) and I was wondering if we could consider revisiting this upgrade (here or in a new PR) to enable this feature for RRFS implementation.

cc @GeorgeGayno-NOAA as we discussed this earlier

**Comment by DavidHuber-NOAA** [comment]
@LarissaReames-NOAA The weather model actually closed that PR as they are planning on moving to spack-stack 1.9.1 instead.  See issue https://github.com/ufs-community/ufs-weather-model/issues/2619.  I'm ~open~ eager to moving forward with 1.9.1 when the weather model is prepared to do the same, but I would prefer not to have multiple repositories on different versions of spack-stack.

**Comment by LarissaReames** [comment]
Ah, thanks for that clarification. I'd missed that it was closed instead of merged.

I understand not wanting to have multiple spack-stack versions. Just out of curiosity, do you have any idea on a timeline for that upgrade to 1.9.1?

**Comment by DavidHuber-NOAA** [comment]
I'm not sure when the weather model will have this done, but I expect that the other components will all be ready to go about a month afterwards.

**Comment by natalie-perlin** [comment]
Could the current UFS_UTILS move to use the spack-stack-1.6.0 environment fms-2024.1? This is the one used by UFS-weather-model currently:  /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/fms-2024.01
It also uses g2/3.5.1, that is sufficient to apply changes for reading large grib2 files.

**Comment by natalie-perlin** [comment]
@DavidHuber-NOAA @LarissaReames-NOAA - I'd be happy to prepare a PR to move ahead with the ./spack-stack-1.6.0/envs/fms-2024.01

**Comment by DavidHuber-NOAA** [comment]
@natalie-perlin That would be a great solution!  If you would open a PR, I would greatly appreciate it 😄

**Comment by natalie-perlin** [comment]
> @natalie-perlin That would be a great solution! If you would open a PR, I would greatly appreciate it 😄

@DavidHuber-NOAA - Preparing the changes to the modulefiles for the platforms. Is stampede still supported? It is not among the ones for the current ufs-weather-model.

**Comment by DavidHuber-NOAA** [comment]
@natalie-perlin I'm not sure about stampede.  @GeorgeGayno-NOAA would know better than me.

**Comment by GeorgeGayno-NOAA** [comment]
> @natalie-perlin I'm not sure about stampede. @GeorgeGayno-NOAA would know better than me.

Stampede is not an officially supported machine.

**Pull request closed without merging**
