### PR TITLE
release/public-v2: reduce optimization on macOS to avoid random segmentation faults

### PR DESCRIPTION
**Pull request by climbfuji**
This PR updates the top-level `CMakeLists.txt` to reduce the optimization on macOS only. This change fixes the random segmentation faults with multiple threads on macOS that both @mkavulich and @climbfuji have seen. I would like to ask @mkavulich to test this on his system and others to make sure it doesn't affect anything (although the changes are such that I am 100% sure they won't).

While this is not an explanation of the problem, we did something similar for ESMF in the past for a similar problem.

Fixes https://github.com/NOAA-EMC/UFS_UTILS/issues/275.

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
Compiled and tested successfully on Jet!  Approving.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by climbfuji** [comment]
@mkavulich Any suggestions on how to proceed with this PR? Thanks!

**Comment by jwolff-ncar** [comment]
Is this ready to be merged?

**Comment by climbfuji** [comment]
> Is this ready to be merged?

From my side yes. If you want to hold back for a bit longer, I am going to run another test on my second mac, first trying to reproduce the issue without the bugfix and then apply the bugfix in this PR. I can merge this PR myself, since it has been approved already.

**Comment by mkavulich** [comment]
@climbfuji This fixed the errors I was seeing on my own machine as well. I directly replicated the original error, recompiled with the new make rules, and the new executable worked correctly. Looks good to go!

**Review by mkavulich — APPROVED** [review]

**Comment by climbfuji** [comment]
Thanks, @mkavulich good to hear. I'll merge it.

**Pull request merged**
