### PR TITLE
Fix segmentation fault in topo filtering code when processing ESG grids

### LINKED ISSUE #236: Filter_topo code seg fault with ESG grid
@JiliDong-NOAA reported a seg fault in the filter_topo code when creating an ESG grid with these dimensions:

- idim=1301
- jdim=600
- delx/dely=0.0145
- target_lon=-97.5
- target_lat=35.5

The error occurs at line 725 of filter_topo.F90.

I am able to reproduce the error on Hera using 'develop' at 005f9a0.  It is due to an out-of-range subscript in this loop:

```
   else
      do t = 1, ntiles
         do j = js, je
            do i = is, ie+1
               dy(i,j,t) = dx(j,i,t)
            enddo
         enddo
      enddo
   endif
```

These arrays are allocated as follows:

```
  !--- compute dx, dy
    allocate(dx(isd:ied,jsd:jed+1,ntiles))
    allocate(dy(isd:ied+1,jsd:jed,ntiles))
```

I suspect the loop assumed square tiles.  But ESG grids can be certainly non-square.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
Fix problem that can happen when processing regional ESG grids.

Fix creation of program namelist in ./ush/fv3gfs_filter_topo.sh.  Corrects
a read failure when using the GNU compiler.

Add new regression test for ESG regional grids. 

Resolves #236

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Is there a test that proves this fix works?

Please add tests for all new PRs...

**Comment by GeorgeGayno-NOAA** [comment]
> Is there a test that proves this fix works?
> 
> Please add tests for all new PRs...

The grid configuration that failed was added as a new regression test (see 47fed2c).   And this regression test was successfully run on Orion, Jet, Hera, WCOSS-Cray and WCOSS-Dell.   However, this test is not automated (via github actions).

**Comment by edwardhartnett** [comment]
Please automate this test.

**Comment by GeorgeGayno-NOAA** [comment]
> Please automate this test.

Do any of the NCEPLIBS have automated tests that I can use as a guide?

**Comment by jwolff-ncar** [comment]
Do you have plans to add this change to the release branch as well? Thanks!

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA take a look at NCEPLIBS-bufr for lots of test examples.

**Comment by edwardhartnett** [comment]
Any progress on automating this test?

**Comment by GeorgeGayno-NOAA** [comment]
> Any progress on automating this test?

No, I have not had time.

**Comment by edwardhartnett** [comment]
Are we going to merge this PR? If we don't have a test, let's get these changes merged and circle around again with the testing.

**Comment by GeorgeGayno-NOAA** [comment]
> Are we going to merge this PR? If we don't have a test, let's get these changes merged and circle around again with the testing.

We don't have an automated test.  But I added a new test under ./reg_tests that will run on our five officially supported machines.

**Comment by edwardhartnett** [comment]
@gsketefian and @JeffBeck-NOAA can you review these changes please?

**Comment by GeorgeGayno-NOAA** [comment]
Let merge from develop to my branch.  Also, I want to run the regression tests on our five machines one final time.

**Comment by edwardhartnett** [comment]
Sorry, I just merged your other PR, which was documentation only. So I updated here again so we can merge.

**Comment by GeorgeGayno-NOAA** [comment]
I compiled the branch at 69fc1b5 on Hera, Jet, Orion, WCOSS-Cray and WCOSS-Dell.  I then ran the grid generation regression tests (./reg_test/grid_gen).  All tests passed on all machines.   I recommend it be merged.

**Comment by edwardhartnett** [comment]
It needs to be reviewed - I can approve it if you want, but you had previous asked for reviews from others - do you want to wait for one of them?

**Comment by GeorgeGayno-NOAA** [comment]
> It needs to be reviewed - I can approve it if you want, but you had previous asked for reviews from others - do you want to wait for one of them?

You can approve it.

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
