### PR TITLE
add tripoletools folder with 3 submodules

### PR DESCRIPTION
**Pull request by DeniseWorthen**
1) CICE5_ICgen: grid generation for cice5/cice6

2) CICE5_gridgen: initial condition generation for cice5/cice6

3) WeightGen: weight generation

a) gen_fixgrid and associated fortran code:
a fortran routine to read the MOM6 supergrid
and create a netcdf file which is the basis for the
remaining transformations

b) generate_iceocn_weights.ncl:
esmf weight generation for tripole:tripole or
tripole:rectilinear or other grid:grid transformations

c) generate_icemesh.ncl:
generation of the ice_mesh for use by the CMEPS mediator

d) generate_frac_land_weights.sh:
generation of the frac_land weights (the ocean mask on the
fv3 grid) using ESMF_RegridWeightGen

d) make_frac_land.ncl:
creation of the 6-tiled land_frac files

Note: these need to be moved into the appropriate places and adjusted for general use. I am happy to work with you on the best way to do this.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
FYI: @junwang-noaa @arunchawla-NOAA

**Comment by GeorgeGayno-NOAA** [comment]
@DeniseWorthen So you are simply adding your code as submodules?  Why does UFS_UTILS need to be involved?

**Comment by DeniseWorthen** [comment]
These need to be integrated into ufs-utils. I do not know where they best belong, or what structure you are using. They also need to be worked with the be of use to a general user. It was my impression that you were expecting to see this as a PR so that we could work together to best figure out how they should be incorporated into ufs-utils.

**Comment by GeorgeGayno-NOAA** [comment]
> These need to be integrated into ufs-utils. I do not know where they best belong, or what structure you are using. They also need to be worked with to be of use to a general user. It was my impression that you were expecting to see this as a PR so that we could work together to best figure out how they should be incorporated into ufs-utils.

Denise, the PR is always the last step after everything has been tested.  Open an issue.  Then, we can discuss the details.  Keep your branch.  But close this PR.

**Pull request closed without merging**
