### PR TITLE
Rearrange allocation of hgt_1d in mtnlm7_oclsm.f to fix errors on MacOS

### PR DESCRIPTION
**Pull request by mkavulich**
There are some declarations of allocatable variables that result in `illegal instruction` errors on MacOS, despite being valid Fortran77 code. One such instance is found in `sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.f`, where the real `hgt_1d` is declared in the subroutine MAKEMT2. While the existing code is valid, it can be rearranged in a way that does not trigger this error but gives equivalent results.

This code has been tested on MacOS (GNU 9.3.0), Cheyenne (GNU 10.1.0) and Hera (Intel 18.0.5) by running the end-to-end UFS SRW App workflow release branch tests. Also checked on Cheyenne to ensure the output files from `orog` for the GST test case were bit-for-bit identical. Let me know if there are any other tests required for this PR to be accepted.

This PR will resolve Issue #243. Thanks to @climbfuji for providing the breadcrumbs needed to find and fix this problem.

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
I would explicitly add the deallocate statement at the end of this routine.

**Comment by GeorgeGayno-NOAA** [comment]
This fix should added 'develop' as well?

**Comment by mkavulich** [comment]
@GeorgeGayno-NOAA Yes I believe this should be added to develop as well, though I have not specifically tried develop on MacOS yet.

**Comment by mkavulich** [comment]
@climbfuji I added the deallocate statement, and re-tested on MacOS and Hera, all successful.

**Review by climbfuji — APPROVED** [review]

**Pull request merged**
