### PR TITLE
Generalize ATM-OCN resolutions for mapped ocean mask generation

### LINKED ISSUE #976: generalize the combinations available for cpld_gridgen
The cpld_gridgen utility currently works only for specified combinations of the ocean and atm. It should be generalized to create any ATM and OCN resolution. This will provide the required mapped ocean mask for any ATM resolution with any OCN resolution. 

Originally these combinations were "pinned" to certain combinations because of the need to generate a set of weights for the CICE IC generation. Since this capability has been replaced by the ocnice_prep utility, all mapped ocean combinations can now be generated at once in cpld_gridgen.

### PR DESCRIPTION
**Pull request by DeniseWorthen**
## DESCRIPTION OF CHANGES: 

The cpld_gridgen code is updated to loop over 6 ATM resolutions (C48, C96, C100, C384, C768 and C1152) and produce the mapped ocean mask for a given OCN resolution. Previously the only supported combinations were C48+5deg ocean, C96+1deg ocean, C192+1/2deg ocean and C384+1/4deg ocean.

The cpld_gridgen regression test scripts were also updated for the new feature. 

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [x] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2). Done using 91a0788.
- [x] Compile branch on Hera using GNU. Done using 91a0788.
- [x] Compile branch in 'Debug' mode on WCOSS2. Done on Cactus using 91a0788.
- [x] Run unit tests locally on any Tier 1 machine. Done on Hera using 91a0788.
- [x] Run relevant `cpld_gridgen` tests locally on all Tier 1 machines. All tests successful using 91a0788. 

Describe any additional tests performed.

This PR adds additional mapped ocean mask files which were not previously generated. Baselines on Hercules-intel and Hera-intel were B4B for the existing mapped ocean mask files. For example, ``C192.mx050.tile[1-6].nc`` currently exists and are B4B with the baseline. ``C[1152, 768, 384, 96, 48].mx050.tile[1-6].nc`` do not currently exist and are now generated. 

## DOCUMENTATION:

A minor documentation update is added.

The Doxygen was built on Cactus using 91a0788. The `cpld_gridgen` section had no warnings.

## ISSUE:
- fixes #976

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@GeorgeGayno-NOAA I see some recent commits that allowed building on Gaea5/6, but we are not yet maintaining baselines there. Is that correct?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I see some recent commits that allowed building on Gaea5/6, but we are not yet maintaining baselines there. Is that correct?

Correct. Gaea is not officially supported. I don't even have access to that machine. Don't worry about that machine.

**Comment by DeniseWorthen** [comment]
I've created and verified baselines on Hera, Hercules and Orion.

hera: /scratch1/NCEPDEV/stmp4/Denise.Worthen/CPLD_GRIDGEN/BASELINE
hercules: /work2/noaa/stmp/dworthen/CPLD_GRIDGEN/BASELINE
orion: /work/noaa/stmp/dworthen/CPLD_GRIDGEN/BASELINE

Jet is just sitting in the Q, and I need to get my WCOSS2 reactivated before running there. I'll update you when I get those two ready.

**Comment by GeorgeGayno-NOAA** [comment]
> I've created and verified baselines on Hera, Hercules and Orion.
> 
> hera: /scratch1/NCEPDEV/stmp4/Denise.Worthen/CPLD_GRIDGEN/BASELINE hercules: /work2/noaa/stmp/dworthen/CPLD_GRIDGEN/BASELINE orion: /work/noaa/stmp/dworthen/CPLD_GRIDGEN/BASELINE
> 
> Jet is just sitting in the Q, and I need to get my WCOSS2 reactivated before running there. I'll update you when I get those two ready.

I will move your baseline files to the official location.

**Comment by DeniseWorthen** [comment]
@GeorgeGayno-NOAA Just an update. I have not successfully been able to run on Jet yet. It is just sitting pending in the Q. I think UFS is having trouble getting anything through the Q on Jet. I'm working on getting WCOSS2 re-activated.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Just an update. I have not successfully been able to run on Jet yet. It is just sitting pending in the Q. I think UFS is having trouble getting anything through the Q on Jet. I'm working on getting WCOSS2 re-activated.

I can't get anything to run either (using the "hfv3gfs" project). I emailed the Jet help desk. Here is what they wrote:

```
The reason why "hfv3gfs" is experiencing long wait times is because Jet has high usage, and "hfv3gfs"'s current fairshare value is low.

Please see the following from a report from yesterday afternoon:

Project: hfv3gfs
----------------------
NormShares: 0.000693
FairShare: 0.000106
Rank: 46/48

Because "hfv3gfs" has a fairshare of "1% of 1%", and a rank of "46/48", the project has to wait to submit jobs when Jet is experiencing high usage.
```

I don't know what project you use, but you can check this info by typing "account_params".

**Comment by DeniseWorthen** [comment]
@GeorgeGayno-NOAA I have a baseline on WCOSS2 now

/lfs/h2/emc/stmp/denise.worthen/CPLD_GRIDGEN/BASELINE

I  use the h-nems account on Jet, but our fairshare is just as low there. Hopefully I'll get the baselines generated at some point.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I have a baseline on WCOSS2 now
> 
> /lfs/h2/emc/stmp/denise.worthen/CPLD_GRIDGEN/BASELINE
> 
> I use the h-nems account on Jet, but our fairshare is just as low there. Hopefully I'll get the baselines generated at some point.

If you think your tests can run in under 30 minutes, try the 'debug' queue. I am getting good turnaround with 'debug' this morning.

**Comment by DeniseWorthen** [comment]
I'll try that, thanks. 

Jet is so small, I don't understand why everyone wants to run there.

**Comment by DeniseWorthen** [comment]
I was able to create a baseline on Jet using the debug Q

/lfs5/HFIP/h-nems/Denise.Worthen/CPLD_GRIDGEN/BASELINE

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I have a baseline on WCOSS2 now
> 
> /lfs/h2/emc/stmp/denise.worthen/CPLD_GRIDGEN/BASELINE
> 
> I use the h-nems account on Jet, but our fairshare is just as low there. Hopefully I'll get the baselines generated at some point.

Sorry, @DeniseWorthen - I got distracted. Can you regenerate your baseline on WCOSS2? Appologies.

**Comment by DeniseWorthen** [comment]
No problem. I'll let you know when they're done.

**Comment by DeniseWorthen** [comment]
I've regenerated WCOSS2 baselines 

```
/lfs/h2/emc/stmp/denise.worthen/CPLD_GRIDGEN/BASELINE/
```

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
Thanks, @DeniseWorthen. Merging now.

**Pull request merged**
