### PR TITLE
Change version number from 1.1.1 to 1.0.0 for UFS release

### PR DESCRIPTION
**Pull request by climbfuji**
Change version number from 1.1.1 to 1.0.0 for UFS release, see discussion in https://github.com/NOAA-EMC/NCEPLIBS/pull/66

### CODE REVIEW

**Comment by climbfuji** [comment]
Thanks. Please approve so that I can merge, or merge by yourself. Yes, unfortunately I have to ask you to recreate the tag. Thanks!

**Comment by climbfuji** [comment]
@GeorgeGayno-NOAA if you could please let me know when the tag has been recreated, I would like to confirm that the head and tag stored in the umbrella build are correct. Thanks very much!

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> @GeorgeGayno-NOAA if you could please let me know when the tag has been recreated, I would like to confirm that the head and tag stored in the umbrella build are correct. Thanks very much!

I recreated the tag.  Can I delete the two 'beta' tags?

**Comment by climbfuji** [comment]
Thanks! The tag looks good. I believe you can delete the beta tags, yes.

**Pull request merged**
