### PR TITLE
Upgrade to spack-stack/1.6.0

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
## DESCRIPTION OF CHANGES: 
This upgrades the libraries for UFS_Utils to those of spack-stack version 1.6.0.  Most notably, this upgrades the following libraries:

- netcdf-fortran 4.6.0 -> 4.6.1
- esmf 8.4.2 -> 8.6.0
- sp 2.3.3 -> 2.5.0

Also, support for Cheyenne is removed as that system has gone offline.

Regression tests on Hera, Orion, Hercules, and Jet all showed the same differences
- Minor differences in U- and V-winds in several chgres tests.  @GeorgeGayno-NOAA confirmed these were minor.
- The `mx100` `cpld_gridgen` test showed differences in `col` and `S` variables.  @DeniseWorthen confirmed these were minor and had to do with the way ESMF regridded the variables.

One test differed on Orion/Hercules, Jet, and WCOSS2:
- The `global_cycle` `C192 landinc soil-NoahMP` test produced identical surface `.inc` files on Hera, but on Orion/Hercules, Jet and 
WCOSS2 the tiled `sfcanl` files had an extra `checksum` attribute in the `hice` and `fice` fields.  However, the values of the fields were identical.  This probably means the baseline data needs to be updated on these platforms.

## TESTS CONDUCTED: 
If there are changes to the build or source code, the tests below must be conducted. Contact a repository manager if you need assistance.

- [x] Compile branch on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2).
- [x] Compile branch on Hera using GNU.
- [x] Compile branch in 'Debug' mode on WCOSS2.
- [x] Run unit tests locally on any Tier 1 machine.
- [x] Run relevant consistency tests locally on all Tier 1 machine.

Describe any additional tests performed.

## ISSUE: 
#884

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
There is a reference to cheyenne in `machine_setup.sh` that you can remove:
https://github.com/DavidHuber-NOAA/UFS_UTILS/blob/ss_160/sorc/machine-setup.sh#L40

**Comment by GeorgeGayno-NOAA** [comment]
The `global_cycle` regression test baseline was recently updated under a previous PR. So, the 'checksum' difference is no longer an issue. When I run your branch (4e6757a) on Hera, all `global_cycle` tests pass.

**Comment by DavidHuber-NOAA** [comment]
> There is a reference to cheyenne in `machine_setup.sh` that you can remove: https://github.com/DavidHuber-NOAA/UFS_UTILS/blob/ss_160/sorc/machine-setup.sh#L40

Done.

> The `global_cycle` regression test baseline was recently updated under a previous PR. So, the 'checksum' difference is no longer an issue. When I run your branch ([4e6757a](https://github.com/ufs-community/UFS_UTILS/commit/4e6757a21119a1b2bb5024193ff3063ba88656ce)) on Hera, all `global_cycle` tests pass.

Noted, thanks for testing.

**Comment by GeorgeGayno-NOAA** [comment]
'develop' was updated this morning. Did you merge these changes to your branch?

**Comment by DavidHuber-NOAA** [comment]
No, but I have now.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Looks good. Will merge.

**Pull request merged**
