### PR TITLE
updated readme with authors of each utility

### LINKED ISSUE #378: List authors of each util in README
Now that we are getting our documentation together, we should be able to list the actual authors in the readme.

I think we need to list the authors of each utility separately.

### LINKED ISSUE #383: Add another code manager to UFS_UTILS
We have all identified the need to have more than one code manager for each repo, but we really don't have many people. ;-)

UFS_UTILS is a very important repo, however, where the rubber meets the road in terms of using some of the other NCEPLIBS libraries. Our documentation and testing work is generating a lot of extra tasks for @GeorgeGayno-NOAA . :-(

Some of this additional effort can be taken on by @kgerheiser who can step in as backup code manager for this repo. It would be useful if Kyle can handle PRs related to testing, build system, etc., and leave the science tasks to George.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Updated README.

Fixes #378
Fixes #383

@GeorgeGayno-NOAA can you tell me the missing authors? I have:

```
### chgres_cube
- George Gayno

### emcsfc_ice_blend
- George Gayno

### emcsfc_snow2mdl
- George Gayno

### fvcom_tools
 - David Wright, University of Michigan
 
### global_cycle
 - ???

### grid_tools
 - R. J. Purser

### orog_mask_tools
 - Ning Wang

### sfc_climo_gen
 - ???

### vcoord_gen
 - ???

```

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
> Updated README.
> 
> Fixes #378
> Fixes #383
> 
> @GeorgeGayno-NOAA can you tell me the missing authors? I have:
> 
> ```
> ### chgres_cube
> - George Gayno
> 
> ### emcsfc_ice_blend
> - George Gayno
> 
> ### emcsfc_snow2mdl
> - George Gayno
> 
> ### fvcom_tools
>  - David Wright, University of Michigan
>  
> ### global_cycle
>  - ???
> 
> ### grid_tools
>  - R. J. Purser
> 
> ### orog_mask_tools
>  - Ning Wang
> 
> ### sfc_climo_gen
>  - ???
> 
> ### vcoord_gen
>  - ???
> ```

For global_cycle it is me and Shrinivas Moorthi.
For sfc_climo_gen it is me.
For vcoord_gen it is Fanglin Yang.

**Comment by GeorgeGayno-NOAA** [comment]
I also list the authors on the ufs_utils wiki page: https://github.com/NOAA-EMC/UFS_UTILS/wiki/5.-Code-Managers-For-Each-Program

Should this wiki page be removed?

**Comment by edwardhartnett** [comment]
No, don't remove from the wiki - more is better!

I will update, thanks.

**Comment by edwardhartnett** [comment]
There are many other contributors to the code, as indicated by GitHub. In software projects, it's customary to list all contributors, not just the primary author of the code. Can you tell me what names should be added to what utils?

**Comment by edwardhartnett** [comment]
Should jordan.alpert and shan.sun be added for orog_mask_tools?

**Comment by GeorgeGayno-NOAA** [comment]
> Should jordan.alpert and shan.sun be added for orog_mask_tools?

Under orog_tools.fd, Jordan Alpert created the orog.fd program.  However, he just retired.  So maybe you can list me for now.  For the inland.fd and lake.fd programs, list Shan Sun and Ning Wang.

**Comment by edwardhartnett** [comment]
We can list Jordan as an author. He's retired, but his contribution continues.

**Comment by GeorgeGayno-NOAA** [comment]
Under grid_tools.fd, the topo filtering code was created by someone at GFDL (I don't know who).  

The global_equiv_resol code was written by Gerard Ketefian of NOAA/GSL.  

The regional_esg_grid code is Jim Purser.  

The shave.fd program is Tom Black, but he retired.  That program is used by the regional group.  Ben Blake is the repo manager for the regional workflow.  I would list him for now.

**Comment by GeorgeGayno-NOAA** [comment]
Jeff Beck and Larissa Reames have made contributions to chgres_cube.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA I've added all your updates. If you can approve the review, I will get this merged.

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Looks good to me.

**Pull request merged**
