### PR TITLE
 move test data to data subdirectory under tests/chgres_cube

### LINKED ISSUE #454: move test data to data subdirectory under tests/chgres_cube
We have some namelist files, and I am adding a varmap file, and there are going to be more data files to come as we add testing.

So I will create a data subdirectory to tests/chgres_cube and we can put our test data there.

I will submit a PR to move existing test data.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #454  

Move test data to data subdirectory under tests/chgres_cube.

### CODE REVIEW

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Ok.

**Comment by kgerheiser** [comment]
Any reason to not copy (or symlink) the whole data directory instead of copying each file individually?

**Comment by kgerheiser** [comment]
```
execute_process(COMMAND cmake -E create_symlink
  "${CMAKE_CURRENT_SOURCE_DIR}/data"
  "${CMAKE_CURRENT_BINARY_DIR}/data" # New name
  )
```

**Comment by edwardhartnett** [comment]
Tried this and it didn't work:
`file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/data DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/data)
`
So I'll merge this PR and we can clean up the CMake file in a future PR.

**Pull request merged**
