### PR TITLE
Eliminate circular dependency in chgres_cube

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
## DESCRIPTION OF CHANGES: 
Remove circular dependency between write_data.F90 and modules surface.F90 and atmosphere.F90

## TESTS CONDUCTED: 
Consistency tests passed on Hera. Tests on other machines are pending.

## DEPENDENCIES:
None.

## DOCUMENTATION:
N/A

## ISSUE: 
#459

## CONTRIBUTORS: 
Many thanks to @kgerheiser for finding this bug and suggesting a solution.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
The consistency tests also passed on Orion, Jet, Venus and Surge.

**Comment by JeffBeck-NOAA** [comment]
@kgerheiser, given your proposed fix to this problem, do you mind reviewing @GeorgeGayno-NOAA's PR?  Thank you!

**Review by LarissaReames — APPROVED** [review]

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
I would like to merge #625 first.

**Comment by GeorgeGayno-NOAA** [comment]
Reran the `chgres_cube` consistency tests using a196559 on Hera, Orion, Jet, WCOSS-Cray and WCOSS-Dell. All tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser You were the one who discovered this bug. Do you want to give your review?

**Review by kgerheiser — APPROVED** [review]

**Pull request merged**
