### PR TITLE
Include fre-nctools.fd in GFS builds

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## DESCRIPTION OF CHANGES: 
GFSv17 plans to use `fregrid` to regrid cube sphere restarts from the deterministic to the ensemble resolution to support snow DA. Currently, when built in the global-workflow, UFS_UTILS does not build `fre-nctools.fd`. This PR updates the CMakeLists.txt to not exclude `fre-nctools.fd` when building with the GFS option.

## TESTS CONDUCTED: 
- [x] Compile branch (normal compilation) on all Tier 1 machines using Intel (Orion, Jet, Hera, Hercules and WCOSS2). Ensure all executables are built.
- [x] Compile branch with 'GFS' build switch ON (any machine). Ensure `fregrid` and other programs used by GFS are created.

Describe any additional tests performed.

## DEPENDENCIES:
None

## DOCUMENTATION:
N/A

## ISSUE: 
No issue was created

## CONTRIBUTORS: 
@jiaruidong2017 helped test and verify that fregrid will work for our needs

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
@CoryMartin-NOAA - I updated the TESTS CONDUCTED section. Let me know if you don't have access to a machine.

**Comment by CoryMartin-NOAA** [comment]
@GeorgeGayno-NOAA I've never logged into Jet but I can test on the others today.

**Comment by CoryMartin-NOAA** [comment]
21 executables are built in `exec` with the default setting:
```
chgres_cube
cpld_gridgen
emcsfc_ice_blend
emcsfc_snow2mdl
filter_topo
fregrid
fvcom_to_FV3
global_cycle
global_equiv_resol
inland
lakefrac
make_hgrid
make_solo_mosaic
ocean_merge
orog
orog_gsl
regional_esg_grid
sfc_climo_gen
shave
vcoord_gen
weight_gen
```
and only 7 (including fregrid) with the GFS option:
```
chgres_cube
emcsfc_ice_blend
emcsfc_snow2mdl
fregrid
global_cycle
make_hgrid
make_solo_mosaic
```

Confirmed on Hera, Orion, Hercules, and Cactus.

**Comment by GeorgeGayno-NOAA** [comment]
> 21 executables are built in `exec` with the default setting:
> 
> ```
> chgres_cube
> cpld_gridgen
> emcsfc_ice_blend
> emcsfc_snow2mdl
> filter_topo
> fregrid
> fvcom_to_FV3
> global_cycle
> global_equiv_resol
> inland
> lakefrac
> make_hgrid
> make_solo_mosaic
> ocean_merge
> orog
> orog_gsl
> regional_esg_grid
> sfc_climo_gen
> shave
> vcoord_gen
> weight_gen
> ```
> 
> and only 7 (including fregrid) with the GFS option:
> 
> ```
> chgres_cube
> emcsfc_ice_blend
> emcsfc_snow2mdl
> fregrid
> global_cycle
> make_hgrid
> make_solo_mosaic
> ```
> 
> Confirmed on Hera, Orion, Hercules, and Cactus.

Confirmed on Jet using 07c6a66.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Comment by GeorgeGayno-NOAA** [comment]
@CoryMartin-NOAA - please merge the latest updates from 'develop' to your branch. Then, I will merge.

**Comment by CoryMartin-NOAA** [comment]
@GeorgeGayno-NOAA develop should be merged in now, thanks!

**Comment by aerorahul** [comment]
@CoryMartin-NOAA 
Does `fregrid` compile without warnings on WCOSS2, with`debug` compiler flags? 
I ask because it will be used for v17 GFS.

**Comment by GeorgeGayno-NOAA** [comment]
> @CoryMartin-NOAA Does `fregrid` compile without warnings on WCOSS2, with`debug` compiler flags? I ask because it will be used for v17 GFS.

When I build the head of 'develop' (3ef2e6b) on WCOSS2 in 'Debug' mode and with `-DGFS=ON`, there are warnings:

```
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/fre-nctools.fd/shared_lib/create_xgrid.c(1602): warning #266: function "insertIntersect" declared implicitly
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/fre-nctools.fd/shared_lib/create_xgrid.c(1605): warning #266: function "insertIntersect" declared implicitly
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/fre-nctools.fd/shared_lib/create_xgrid.c(1619): warning #266: function "insertIntersect" declared implicitly
/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/UFS_UTILS/sorc/fre-nctools.fd/shared_lib/create_xgrid.c(1621): warning #266: function "insertIntersect" declared implicitly
```

These warnings will be removed under #959.

I get other warnings, but I don't know how to fix them:

```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.62, needed by /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.so, may conflict with libjpeg.so.9
```

**Pull request merged**
