### PR TITLE
Make intermediate library for executables for easier testing

### LINKED ISSUE #446: Create libraries so code can be more easily used for testing
The CMake build should build a library for each executable before linking in the final `program` or `main`. This allows the same compiled code to be more easily used for testing instead of duplicating the compilation and build flags when building tests.

For example, any tests for chgres-cube will link to `chgres_cube_lib` which includes all the code except the driver program.

This change will be completely transparent and only changes how intermediate build products are stored.

### PR DESCRIPTION
**Pull request by kgerheiser**
This will make writing tests easier as you don't have to duplicate compilation and linking, and just use the library created for each utility.

Fixes #446

### CODE REVIEW

**Review by edwardhartnett — APPROVED** [review]
Excellent. 

Can you enter an issue for this, briefly describing it?

Also please add your name to the list of authors of the cmake files, since you are making significant edits.

**Comment by kgerheiser** [comment]
Ready to be merged.

The end result is that this:

```
add_executable(ftst_program_setup "${CMAKE_SOURCE_DIR}/sorc/chgres_cube.fd/input_data.F90"
   "${CMAKE_SOURCE_DIR}/sorc/chgres_cube.fd/model_grid.F90"
   "${CMAKE_SOURCE_DIR}/sorc/chgres_cube.fd/program_setup.F90"
   "${CMAKE_SOURCE_DIR}/sorc/chgres_cube.fd/grib2_util.F90"
   "${CMAKE_SOURCE_DIR}/sorc/chgres_cube.fd/search_util.F90"
   "${CMAKE_SOURCE_DIR}/sorc/chgres_cube.fd/utils.F90"
   ftst_program_setup.F90)
 target_link_libraries(
   ftst_program_setup
   nemsio::nemsio
   sfcio::sfcio
   sigio::sigio
   bacio::bacio_4
   sp::sp_d
   w3nco::w3nco_d
   esmf
   wgrib2::wgrib2_lib
   wgrib2::wgrib2_api
   MPI::MPI_Fortran
   NetCDF::NetCDF_Fortran)
 if(OpenMP_Fortran_FOUND)
   target_link_libraries(ftst_program_setup OpenMP::OpenMP_Fortran)
 endif()
```

Became this:

```
add_executable(ftst_program_setup ftst_program_setup.F90)
target_link_libraries(ftst_program_setup chgres_cube_lib)
```

**Comment by edwardhartnett** [comment]
I knew all along that this should be done, but I just wasn't good enough at cmake to do it. ;-) Thanks, I will study the result and try to learn...

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser I just discovered a small glitch. The 'inland' and 'lake_frac' programs are being built, but the 'install' is not working. If I build the previous commit of develop (123759a), I get this in ./exec:

```
exec.orig:
chgres_cube       emcsfc_snow2mdl  fregrid       global_cycle        inland    make_hgrid        orog      regional_esg_grid  shave
emcsfc_ice_blend  filter_topo      fvcom_to_FV3  global_equiv_resol  lakefrac  make_solo_mosaic  orog_gsl  sfc_climo_gen      vcoord_gen
```

Using ea82135, I get:

```
exec:
chgres_cube       emcsfc_snow2mdl  fregrid       global_cycle        make_hgrid        orog      regional_esg_grid  shave
emcsfc_ice_blend  filter_topo      fvcom_to_FV3  global_equiv_resol  make_solo_mosaic  orog_gsl  sfc_climo_gen      vcoord_gen
```

**Pull request merged**
